//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfRPropertyTareTableItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfRPropertyTareTableItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RPropertyTareTableItem" type="{http://tempuri.org/}RPropertyTareTableItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfRPropertyTareTableItem", propOrder = {
    "rPropertyTareTableItem"
})
public class ArrayOfRPropertyTareTableItem {

    @XmlElement(name = "RPropertyTareTableItem", nillable = true)
    protected List<RPropertyTareTableItem> rPropertyTareTableItem;

    /**
     * Gets the value of the rPropertyTareTableItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rPropertyTareTableItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRPropertyTareTableItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RPropertyTareTableItem }
     * 
     * 
     */
    public List<RPropertyTareTableItem> getRPropertyTareTableItem() {
        if (rPropertyTareTableItem == null) {
            rPropertyTareTableItem = new ArrayList<RPropertyTareTableItem>();
        }
        return this.rPropertyTareTableItem;
    }

}
