//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfROnlineInfo1C complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfROnlineInfo1C"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ROnlineInfo1C" type="{http://tempuri.org/}ROnlineInfo1C" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfROnlineInfo1C", propOrder = {
    "rOnlineInfo1C"
})
public class ArrayOfROnlineInfo1C {

    @XmlElement(name = "ROnlineInfo1C", nillable = true)
    protected List<ROnlineInfo1C> rOnlineInfo1C;

    /**
     * Gets the value of the rOnlineInfo1C property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rOnlineInfo1C property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getROnlineInfo1C().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ROnlineInfo1C }
     * 
     * 
     */
    public List<ROnlineInfo1C> getROnlineInfo1C() {
        if (rOnlineInfo1C == null) {
            rOnlineInfo1C = new ArrayList<ROnlineInfo1C>();
        }
        return this.rOnlineInfo1C;
    }

}
