//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="router" type="{http://tempuri.org/}RouterType"/&gt;
 *         &lt;element name="waypoints" type="{http://tempuri.org/}ArrayOfRPoint" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "router",
    "waypoints"
})
@XmlRootElement(name = "GetRoute")
public class GetRoute {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RouterType router;
    protected ArrayOfRPoint waypoints;

    /**
     * Gets the value of the router property.
     * 
     * @return
     *     possible object is
     *     {@link RouterType }
     *     
     */
    public RouterType getRouter() {
        return router;
    }

    /**
     * Sets the value of the router property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouterType }
     *     
     */
    public void setRouter(RouterType value) {
        this.router = value;
    }

    /**
     * Gets the value of the waypoints property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRPoint }
     *     
     */
    public ArrayOfRPoint getWaypoints() {
        return waypoints;
    }

    /**
     * Sets the value of the waypoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRPoint }
     *     
     */
    public void setWaypoints(ArrayOfRPoint value) {
        this.waypoints = value;
    }

}
