//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MRuleNotifyTarget1C complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MRuleNotifyTarget1C"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Item" type="{http://tempuri.org/}RMonitoringNotifyItem" minOccurs="0"/&gt;
 *         &lt;element name="NotifyType" type="{http://tempuri.org/}RMonitoringNotifyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MRuleNotifyTarget1C", propOrder = {
    "item",
    "notifyType"
})
public class MRuleNotifyTarget1C {

    @XmlElement(name = "Item")
    protected RMonitoringNotifyItem item;
    @XmlList
    @XmlElement(name = "NotifyType", required = true)
    protected List<String> notifyType;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link RMonitoringNotifyItem }
     *     
     */
    public RMonitoringNotifyItem getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMonitoringNotifyItem }
     *     
     */
    public void setItem(RMonitoringNotifyItem value) {
        this.item = value;
    }

    /**
     * Gets the value of the notifyType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notifyType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotifyType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNotifyType() {
        if (notifyType == null) {
            notifyType = new ArrayList<String>();
        }
        return this.notifyType;
    }

}
