//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.tdv.soapclient.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RTrip1CSD1_QNAME = new QName("http://tempuri.org/", "_SD");
    private final static QName _RTrip1CED1_QNAME = new QName("http://tempuri.org/", "_ED");
    private final static QName _RTrip1CIndex_QNAME = new QName("http://tempuri.org/", "Index");
    private final static QName _RTrip1CED2_QNAME = new QName("http://tempuri.org/", "SD");
    private final static QName _RTrip1CEE2_QNAME = new QName("http://tempuri.org/", "ED");
    private final static QName _RTrip1CPointStart_QNAME = new QName("http://tempuri.org/", "PointStart");
    private final static QName _RTrip1CPointEnd_QNAME = new QName("http://tempuri.org/", "PointEnd");
    private final static QName _RTrip1CStages_QNAME = new QName("http://tempuri.org/", "Stages");
    private final static QName _RTrip1CTotal_QNAME = new QName("http://tempuri.org/", "Total");
    private final static QName _RTrip1CAreas_QNAME = new QName("http://tempuri.org/", "Areas");
    private final static QName _LastCoords1_QNAME = new QName("http://tempuri.org/", "_LastCoords");
    private final static QName _LastData1_QNAME = new QName("http://tempuri.org/", "_LastData");
    private final static QName _RTrips1CID_QNAME = new QName("http://tempuri.org/", "ID");
    private final static QName _RTrips1CName_QNAME = new QName("http://tempuri.org/", "Name");
    private final static QName _RTrips1CSerial_QNAME = new QName("http://tempuri.org/", "Serial");
    private final static QName _RTrips1CVRN_QNAME = new QName("http://tempuri.org/", "VRN");
    private final static QName _RTrips1CTrips_QNAME = new QName("http://tempuri.org/", "Trips");
    private final static QName _RTrips1CLastPosition_QNAME = new QName("http://tempuri.org/", "LastPosition");
    private final static QName _RTrips1CLastCoords_QNAME = new QName("http://tempuri.org/", "LastCoords");
    private final static QName _RTrips1CLastData_QNAME = new QName("http://tempuri.org/", "LastData");
    private final static QName _RTripStageItemStatus_QNAME = new QName("http://tempuri.org/", "Status");
    private final static QName _RTripStageItemStatusID_QNAME = new QName("http://tempuri.org/", "StatusID");
    private final static QName _RTripStageItemStatusIDs_QNAME = new QName("http://tempuri.org/", "StatusIDs");
    private final static QName _RTripStageItemStartPoint_QNAME = new QName("http://tempuri.org/", "StartPoint");
    private final static QName _RTripStageItemEndPoint_QNAME = new QName("http://tempuri.org/", "EndPoint");
    private final static QName _RTripStageItemCaption_QNAME = new QName("http://tempuri.org/", "Caption");
    private final static QName _RTripStageItemValues_QNAME = new QName("http://tempuri.org/", "Values");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.tdv.soapclient.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

    /**
     * Create an instance of {@link Test2 }
     * 
     */
    public Test2 createTest2() {
        return new Test2();
    }

    /**
     * Create an instance of {@link Test2Response }
     * 
     */
    public Test2Response createTest2Response() {
        return new Test2Response();
    }

    /**
     * Create an instance of {@link RPropertyTareTable }
     * 
     */
    public RPropertyTareTable createRPropertyTareTable() {
        return new RPropertyTareTable();
    }

    /**
     * Create an instance of {@link UserDelete }
     * 
     */
    public UserDelete createUserDelete() {
        return new UserDelete();
    }

    /**
     * Create an instance of {@link ArrayOfGuid }
     * 
     */
    public ArrayOfGuid createArrayOfGuid() {
        return new ArrayOfGuid();
    }

    /**
     * Create an instance of {@link UserDeleteResponse }
     * 
     */
    public UserDeleteResponse createUserDeleteResponse() {
        return new UserDeleteResponse();
    }

    /**
     * Create an instance of {@link EnumRoles }
     * 
     */
    public EnumRoles createEnumRoles() {
        return new EnumRoles();
    }

    /**
     * Create an instance of {@link EnumRolesResponse }
     * 
     */
    public EnumRolesResponse createEnumRolesResponse() {
        return new EnumRolesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRRole }
     * 
     */
    public ArrayOfRRole createArrayOfRRole() {
        return new ArrayOfRRole();
    }

    /**
     * Create an instance of {@link EnumUsers }
     * 
     */
    public EnumUsers createEnumUsers() {
        return new EnumUsers();
    }

    /**
     * Create an instance of {@link EnumUsersResponse }
     * 
     */
    public EnumUsersResponse createEnumUsersResponse() {
        return new EnumUsersResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRUser }
     * 
     */
    public ArrayOfRUser createArrayOfRUser() {
        return new ArrayOfRUser();
    }

    /**
     * Create an instance of {@link EnumUsersAll }
     * 
     */
    public EnumUsersAll createEnumUsersAll() {
        return new EnumUsersAll();
    }

    /**
     * Create an instance of {@link EnumUsersAllResponse }
     * 
     */
    public EnumUsersAllResponse createEnumUsersAllResponse() {
        return new EnumUsersAllResponse();
    }

    /**
     * Create an instance of {@link OTLCreate }
     * 
     */
    public OTLCreate createOTLCreate() {
        return new OTLCreate();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link OTLCreateResponse }
     * 
     */
    public OTLCreateResponse createOTLCreateResponse() {
        return new OTLCreateResponse();
    }

    /**
     * Create an instance of {@link OTLDelete }
     * 
     */
    public OTLDelete createOTLDelete() {
        return new OTLDelete();
    }

    /**
     * Create an instance of {@link OTLDeleteResponse }
     * 
     */
    public OTLDeleteResponse createOTLDeleteResponse() {
        return new OTLDeleteResponse();
    }

    /**
     * Create an instance of {@link UserUpdate }
     * 
     */
    public UserUpdate createUserUpdate() {
        return new UserUpdate();
    }

    /**
     * Create an instance of {@link RUser }
     * 
     */
    public RUser createRUser() {
        return new RUser();
    }

    /**
     * Create an instance of {@link UserUpdateResponse }
     * 
     */
    public UserUpdateResponse createUserUpdateResponse() {
        return new UserUpdateResponse();
    }

    /**
     * Create an instance of {@link EnumDevices }
     * 
     */
    public EnumDevices createEnumDevices() {
        return new EnumDevices();
    }

    /**
     * Create an instance of {@link EnumDevicesResponse }
     * 
     */
    public EnumDevicesResponse createEnumDevicesResponse() {
        return new EnumDevicesResponse();
    }

    /**
     * Create an instance of {@link REnumDevices }
     * 
     */
    public REnumDevices createREnumDevices() {
        return new REnumDevices();
    }

    /**
     * Create an instance of {@link EnumDrivers }
     * 
     */
    public EnumDrivers createEnumDrivers() {
        return new EnumDrivers();
    }

    /**
     * Create an instance of {@link EnumDriversResponse }
     * 
     */
    public EnumDriversResponse createEnumDriversResponse() {
        return new EnumDriversResponse();
    }

    /**
     * Create an instance of {@link REnumDrivers }
     * 
     */
    public REnumDrivers createREnumDrivers() {
        return new REnumDrivers();
    }

    /**
     * Create an instance of {@link EnumGeoFences }
     * 
     */
    public EnumGeoFences createEnumGeoFences() {
        return new EnumGeoFences();
    }

    /**
     * Create an instance of {@link EnumGeoFencesResponse }
     * 
     */
    public EnumGeoFencesResponse createEnumGeoFencesResponse() {
        return new EnumGeoFencesResponse();
    }

    /**
     * Create an instance of {@link REnumGeofences }
     * 
     */
    public REnumGeofences createREnumGeofences() {
        return new REnumGeofences();
    }

    /**
     * Create an instance of {@link EnumImplements }
     * 
     */
    public EnumImplements createEnumImplements() {
        return new EnumImplements();
    }

    /**
     * Create an instance of {@link EnumImplementsResponse }
     * 
     */
    public EnumImplementsResponse createEnumImplementsResponse() {
        return new EnumImplementsResponse();
    }

    /**
     * Create an instance of {@link REnumImplements }
     * 
     */
    public REnumImplements createREnumImplements() {
        return new REnumImplements();
    }

    /**
     * Create an instance of {@link EnumParameters }
     * 
     */
    public EnumParameters createEnumParameters() {
        return new EnumParameters();
    }

    /**
     * Create an instance of {@link EnumParametersResponse }
     * 
     */
    public EnumParametersResponse createEnumParametersResponse() {
        return new EnumParametersResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRParameters }
     * 
     */
    public ArrayOfRParameters createArrayOfRParameters() {
        return new ArrayOfRParameters();
    }

    /**
     * Create an instance of {@link EnumSchemas }
     * 
     */
    public EnumSchemas createEnumSchemas() {
        return new EnumSchemas();
    }

    /**
     * Create an instance of {@link EnumSchemasResponse }
     * 
     */
    public EnumSchemasResponse createEnumSchemasResponse() {
        return new EnumSchemasResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRSchema }
     * 
     */
    public ArrayOfRSchema createArrayOfRSchema() {
        return new ArrayOfRSchema();
    }

    /**
     * Create an instance of {@link EnumStatuses }
     * 
     */
    public EnumStatuses createEnumStatuses() {
        return new EnumStatuses();
    }

    /**
     * Create an instance of {@link EnumStatusesResponse }
     * 
     */
    public EnumStatusesResponse createEnumStatusesResponse() {
        return new EnumStatusesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRDeviceStatus }
     * 
     */
    public ArrayOfRDeviceStatus createArrayOfRDeviceStatus() {
        return new ArrayOfRDeviceStatus();
    }

    /**
     * Create an instance of {@link GetDataRanges }
     * 
     */
    public GetDataRanges createGetDataRanges() {
        return new GetDataRanges();
    }

    /**
     * Create an instance of {@link GetDataRangesResponse }
     * 
     */
    public GetDataRangesResponse createGetDataRangesResponse() {
        return new GetDataRangesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRDataRange }
     * 
     */
    public ArrayOfRDataRange createArrayOfRDataRange() {
        return new ArrayOfRDataRange();
    }

    /**
     * Create an instance of {@link GetDevicesInfo }
     * 
     */
    public GetDevicesInfo createGetDevicesInfo() {
        return new GetDevicesInfo();
    }

    /**
     * Create an instance of {@link GetDevicesInfoResponse }
     * 
     */
    public GetDevicesInfoResponse createGetDevicesInfoResponse() {
        return new GetDevicesInfoResponse();
    }

    /**
     * Create an instance of {@link RDeviceInfo }
     * 
     */
    public RDeviceInfo createRDeviceInfo() {
        return new RDeviceInfo();
    }

    /**
     * Create an instance of {@link GetGeofences }
     * 
     */
    public GetGeofences createGetGeofences() {
        return new GetGeofences();
    }

    /**
     * Create an instance of {@link GetGeofencesResponse }
     * 
     */
    public GetGeofencesResponse createGetGeofencesResponse() {
        return new GetGeofencesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRGeoFence }
     * 
     */
    public ArrayOfRGeoFence createArrayOfRGeoFence() {
        return new ArrayOfRGeoFence();
    }

    /**
     * Create an instance of {@link GetOnlineInfo }
     * 
     */
    public GetOnlineInfo createGetOnlineInfo() {
        return new GetOnlineInfo();
    }

    /**
     * Create an instance of {@link GetOnlineInfoResponse }
     * 
     */
    public GetOnlineInfoResponse createGetOnlineInfoResponse() {
        return new GetOnlineInfoResponse();
    }

    /**
     * Create an instance of {@link ArrayOfROnlineInfo1C }
     * 
     */
    public ArrayOfROnlineInfo1C createArrayOfROnlineInfo1C() {
        return new ArrayOfROnlineInfo1C();
    }

    /**
     * Create an instance of {@link GetOnlineInfoAll }
     * 
     */
    public GetOnlineInfoAll createGetOnlineInfoAll() {
        return new GetOnlineInfoAll();
    }

    /**
     * Create an instance of {@link GetOnlineInfoAllResponse }
     * 
     */
    public GetOnlineInfoAllResponse createGetOnlineInfoAllResponse() {
        return new GetOnlineInfoAllResponse();
    }

    /**
     * Create an instance of {@link GetRoute }
     * 
     */
    public GetRoute createGetRoute() {
        return new GetRoute();
    }

    /**
     * Create an instance of {@link ArrayOfRPoint }
     * 
     */
    public ArrayOfRPoint createArrayOfRPoint() {
        return new ArrayOfRPoint();
    }

    /**
     * Create an instance of {@link GetRouteResponse }
     * 
     */
    public GetRouteResponse createGetRouteResponse() {
        return new GetRouteResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRRouteSegment }
     * 
     */
    public ArrayOfRRouteSegment createArrayOfRRouteSegment() {
        return new ArrayOfRRouteSegment();
    }

    /**
     * Create an instance of {@link GetStage }
     * 
     */
    public GetStage createGetStage() {
        return new GetStage();
    }

    /**
     * Create an instance of {@link GetStageResponse }
     * 
     */
    public GetStageResponse createGetStageResponse() {
        return new GetStageResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRTripStage1C }
     * 
     */
    public ArrayOfRTripStage1C createArrayOfRTripStage1C() {
        return new ArrayOfRTripStage1C();
    }

    /**
     * Create an instance of {@link GetTrack }
     * 
     */
    public GetTrack createGetTrack() {
        return new GetTrack();
    }

    /**
     * Create an instance of {@link GetTrackResponse }
     * 
     */
    public GetTrackResponse createGetTrackResponse() {
        return new GetTrackResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRTrackInfo1C }
     * 
     */
    public ArrayOfRTrackInfo1C createArrayOfRTrackInfo1C() {
        return new ArrayOfRTrackInfo1C();
    }

    /**
     * Create an instance of {@link MRuleDelete }
     * 
     */
    public MRuleDelete createMRuleDelete() {
        return new MRuleDelete();
    }

    /**
     * Create an instance of {@link MRuleDeleteResponse }
     * 
     */
    public MRuleDeleteResponse createMRuleDeleteResponse() {
        return new MRuleDeleteResponse();
    }

    /**
     * Create an instance of {@link MRuleUpdate }
     * 
     */
    public MRuleUpdate createMRuleUpdate() {
        return new MRuleUpdate();
    }

    /**
     * Create an instance of {@link ArrayOfRMonitoringRule1C }
     * 
     */
    public ArrayOfRMonitoringRule1C createArrayOfRMonitoringRule1C() {
        return new ArrayOfRMonitoringRule1C();
    }

    /**
     * Create an instance of {@link MRuleUpdateResponse }
     * 
     */
    public MRuleUpdateResponse createMRuleUpdateResponse() {
        return new MRuleUpdateResponse();
    }

    /**
     * Create an instance of {@link GetNotes }
     * 
     */
    public GetNotes createGetNotes() {
        return new GetNotes();
    }

    /**
     * Create an instance of {@link GetNotesResponse }
     * 
     */
    public GetNotesResponse createGetNotesResponse() {
        return new GetNotesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRNote1C }
     * 
     */
    public ArrayOfRNote1C createArrayOfRNote1C() {
        return new ArrayOfRNote1C();
    }

    /**
     * Create an instance of {@link GetProperties }
     * 
     */
    public GetProperties createGetProperties() {
        return new GetProperties();
    }

    /**
     * Create an instance of {@link GetPropertiesResponse }
     * 
     */
    public GetPropertiesResponse createGetPropertiesResponse() {
        return new GetPropertiesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRProperties1C }
     * 
     */
    public ArrayOfRProperties1C createArrayOfRProperties1C() {
        return new ArrayOfRProperties1C();
    }

    /**
     * Create an instance of {@link GetGFProperties }
     * 
     */
    public GetGFProperties createGetGFProperties() {
        return new GetGFProperties();
    }

    /**
     * Create an instance of {@link GetGFPropertiesResponse }
     * 
     */
    public GetGFPropertiesResponse createGetGFPropertiesResponse() {
        return new GetGFPropertiesResponse();
    }

    /**
     * Create an instance of {@link GetDriverProperties }
     * 
     */
    public GetDriverProperties createGetDriverProperties() {
        return new GetDriverProperties();
    }

    /**
     * Create an instance of {@link GetDriverPropertiesResponse }
     * 
     */
    public GetDriverPropertiesResponse createGetDriverPropertiesResponse() {
        return new GetDriverPropertiesResponse();
    }

    /**
     * Create an instance of {@link GetImplementProperties }
     * 
     */
    public GetImplementProperties createGetImplementProperties() {
        return new GetImplementProperties();
    }

    /**
     * Create an instance of {@link GetImplementPropertiesResponse }
     * 
     */
    public GetImplementPropertiesResponse createGetImplementPropertiesResponse() {
        return new GetImplementPropertiesResponse();
    }

    /**
     * Create an instance of {@link GetProperty }
     * 
     */
    public GetProperty createGetProperty() {
        return new GetProperty();
    }

    /**
     * Create an instance of {@link GetPropertyResponse }
     * 
     */
    public GetPropertyResponse createGetPropertyResponse() {
        return new GetPropertyResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRPropertyItem1C }
     * 
     */
    public ArrayOfRPropertyItem1C createArrayOfRPropertyItem1C() {
        return new ArrayOfRPropertyItem1C();
    }

    /**
     * Create an instance of {@link GetGFProperty }
     * 
     */
    public GetGFProperty createGetGFProperty() {
        return new GetGFProperty();
    }

    /**
     * Create an instance of {@link GetGFPropertyResponse }
     * 
     */
    public GetGFPropertyResponse createGetGFPropertyResponse() {
        return new GetGFPropertyResponse();
    }

    /**
     * Create an instance of {@link GetDriverProperty }
     * 
     */
    public GetDriverProperty createGetDriverProperty() {
        return new GetDriverProperty();
    }

    /**
     * Create an instance of {@link GetDriverPropertyResponse }
     * 
     */
    public GetDriverPropertyResponse createGetDriverPropertyResponse() {
        return new GetDriverPropertyResponse();
    }

    /**
     * Create an instance of {@link GetImplementProperty }
     * 
     */
    public GetImplementProperty createGetImplementProperty() {
        return new GetImplementProperty();
    }

    /**
     * Create an instance of {@link GetImplementPropertyResponse }
     * 
     */
    public GetImplementPropertyResponse createGetImplementPropertyResponse() {
        return new GetImplementPropertyResponse();
    }

    /**
     * Create an instance of {@link SetProperties }
     * 
     */
    public SetProperties createSetProperties() {
        return new SetProperties();
    }

    /**
     * Create an instance of {@link ArrayOfRPropertySetItem1C }
     * 
     */
    public ArrayOfRPropertySetItem1C createArrayOfRPropertySetItem1C() {
        return new ArrayOfRPropertySetItem1C();
    }

    /**
     * Create an instance of {@link SetPropertiesResponse }
     * 
     */
    public SetPropertiesResponse createSetPropertiesResponse() {
        return new SetPropertiesResponse();
    }

    /**
     * Create an instance of {@link SetGFProperties }
     * 
     */
    public SetGFProperties createSetGFProperties() {
        return new SetGFProperties();
    }

    /**
     * Create an instance of {@link SetGFPropertiesResponse }
     * 
     */
    public SetGFPropertiesResponse createSetGFPropertiesResponse() {
        return new SetGFPropertiesResponse();
    }

    /**
     * Create an instance of {@link SetDriverProperties }
     * 
     */
    public SetDriverProperties createSetDriverProperties() {
        return new SetDriverProperties();
    }

    /**
     * Create an instance of {@link SetDriverPropertiesResponse }
     * 
     */
    public SetDriverPropertiesResponse createSetDriverPropertiesResponse() {
        return new SetDriverPropertiesResponse();
    }

    /**
     * Create an instance of {@link SetImplementProperties }
     * 
     */
    public SetImplementProperties createSetImplementProperties() {
        return new SetImplementProperties();
    }

    /**
     * Create an instance of {@link SetImplementPropertiesResponse }
     * 
     */
    public SetImplementPropertiesResponse createSetImplementPropertiesResponse() {
        return new SetImplementPropertiesResponse();
    }

    /**
     * Create an instance of {@link SetProperty }
     * 
     */
    public SetProperty createSetProperty() {
        return new SetProperty();
    }

    /**
     * Create an instance of {@link SetPropertyResponse }
     * 
     */
    public SetPropertyResponse createSetPropertyResponse() {
        return new SetPropertyResponse();
    }

    /**
     * Create an instance of {@link SetGFProperty }
     * 
     */
    public SetGFProperty createSetGFProperty() {
        return new SetGFProperty();
    }

    /**
     * Create an instance of {@link SetGFPropertyResponse }
     * 
     */
    public SetGFPropertyResponse createSetGFPropertyResponse() {
        return new SetGFPropertyResponse();
    }

    /**
     * Create an instance of {@link SetDriverProperty }
     * 
     */
    public SetDriverProperty createSetDriverProperty() {
        return new SetDriverProperty();
    }

    /**
     * Create an instance of {@link SetDriverPropertyResponse }
     * 
     */
    public SetDriverPropertyResponse createSetDriverPropertyResponse() {
        return new SetDriverPropertyResponse();
    }

    /**
     * Create an instance of {@link SetImplementProperty }
     * 
     */
    public SetImplementProperty createSetImplementProperty() {
        return new SetImplementProperty();
    }

    /**
     * Create an instance of {@link SetImplementPropertyResponse }
     * 
     */
    public SetImplementPropertyResponse createSetImplementPropertyResponse() {
        return new SetImplementPropertyResponse();
    }

    /**
     * Create an instance of {@link EnumReports }
     * 
     */
    public EnumReports createEnumReports() {
        return new EnumReports();
    }

    /**
     * Create an instance of {@link EnumReportsResponse }
     * 
     */
    public EnumReportsResponse createEnumReportsResponse() {
        return new EnumReportsResponse();
    }

    /**
     * Create an instance of {@link EnumReportSchedules }
     * 
     */
    public EnumReportSchedules createEnumReportSchedules() {
        return new EnumReportSchedules();
    }

    /**
     * Create an instance of {@link EnumReportSchedulesResponse }
     * 
     */
    public EnumReportSchedulesResponse createEnumReportSchedulesResponse() {
        return new EnumReportSchedulesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRReportScheduleItem }
     * 
     */
    public ArrayOfRReportScheduleItem createArrayOfRReportScheduleItem() {
        return new ArrayOfRReportScheduleItem();
    }

    /**
     * Create an instance of {@link GetReports }
     * 
     */
    public GetReports createGetReports() {
        return new GetReports();
    }

    /**
     * Create an instance of {@link GetReportsResponse }
     * 
     */
    public GetReportsResponse createGetReportsResponse() {
        return new GetReportsResponse();
    }

    /**
     * Create an instance of {@link ArrayOfGetReportResult1C }
     * 
     */
    public ArrayOfGetReportResult1C createArrayOfGetReportResult1C() {
        return new ArrayOfGetReportResult1C();
    }

    /**
     * Create an instance of {@link GetReport }
     * 
     */
    public GetReport createGetReport() {
        return new GetReport();
    }

    /**
     * Create an instance of {@link GetReportResponse }
     * 
     */
    public GetReportResponse createGetReportResponse() {
        return new GetReportResponse();
    }

    /**
     * Create an instance of {@link EnumTasks }
     * 
     */
    public EnumTasks createEnumTasks() {
        return new EnumTasks();
    }

    /**
     * Create an instance of {@link EnumTasksResponse }
     * 
     */
    public EnumTasksResponse createEnumTasksResponse() {
        return new EnumTasksResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRTaskInfo1C }
     * 
     */
    public ArrayOfRTaskInfo1C createArrayOfRTaskInfo1C() {
        return new ArrayOfRTaskInfo1C();
    }

    /**
     * Create an instance of {@link GetTripItems }
     * 
     */
    public GetTripItems createGetTripItems() {
        return new GetTripItems();
    }

    /**
     * Create an instance of {@link GetTripItemsResponse }
     * 
     */
    public GetTripItemsResponse createGetTripItemsResponse() {
        return new GetTripItemsResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRTripItemContainer }
     * 
     */
    public ArrayOfRTripItemContainer createArrayOfRTripItemContainer() {
        return new ArrayOfRTripItemContainer();
    }

    /**
     * Create an instance of {@link GetTrips }
     * 
     */
    public GetTrips createGetTrips() {
        return new GetTrips();
    }

    /**
     * Create an instance of {@link GetTripsResponse }
     * 
     */
    public GetTripsResponse createGetTripsResponse() {
        return new GetTripsResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRTrips1C }
     * 
     */
    public ArrayOfRTrips1C createArrayOfRTrips1C() {
        return new ArrayOfRTrips1C();
    }

    /**
     * Create an instance of {@link GetTripsBatch }
     * 
     */
    public GetTripsBatch createGetTripsBatch() {
        return new GetTripsBatch();
    }

    /**
     * Create an instance of {@link ArrayOfRTripRequest }
     * 
     */
    public ArrayOfRTripRequest createArrayOfRTripRequest() {
        return new ArrayOfRTripRequest();
    }

    /**
     * Create an instance of {@link GetTripsBatchResponse }
     * 
     */
    public GetTripsBatchResponse createGetTripsBatchResponse() {
        return new GetTripsBatchResponse();
    }

    /**
     * Create an instance of {@link GetTripsTotal }
     * 
     */
    public GetTripsTotal createGetTripsTotal() {
        return new GetTripsTotal();
    }

    /**
     * Create an instance of {@link GetTripsTotalResponse }
     * 
     */
    public GetTripsTotalResponse createGetTripsTotalResponse() {
        return new GetTripsTotalResponse();
    }

    /**
     * Create an instance of {@link GetTripsByPeriod }
     * 
     */
    public GetTripsByPeriod createGetTripsByPeriod() {
        return new GetTripsByPeriod();
    }

    /**
     * Create an instance of {@link GetTripsByPeriodResponse }
     * 
     */
    public GetTripsByPeriodResponse createGetTripsByPeriodResponse() {
        return new GetTripsByPeriodResponse();
    }

    /**
     * Create an instance of {@link GetTripsMobileCheckpoints }
     * 
     */
    public GetTripsMobileCheckpoints createGetTripsMobileCheckpoints() {
        return new GetTripsMobileCheckpoints();
    }

    /**
     * Create an instance of {@link GetTripsMobileCheckpointsResponse }
     * 
     */
    public GetTripsMobileCheckpointsResponse createGetTripsMobileCheckpointsResponse() {
        return new GetTripsMobileCheckpointsResponse();
    }

    /**
     * Create an instance of {@link GetTripsArea }
     * 
     */
    public GetTripsArea createGetTripsArea() {
        return new GetTripsArea();
    }

    /**
     * Create an instance of {@link GetTripsAreaResponse }
     * 
     */
    public GetTripsAreaResponse createGetTripsAreaResponse() {
        return new GetTripsAreaResponse();
    }

    /**
     * Create an instance of {@link GetTripsAreaTotal }
     * 
     */
    public GetTripsAreaTotal createGetTripsAreaTotal() {
        return new GetTripsAreaTotal();
    }

    /**
     * Create an instance of {@link GetTripsAreaTotalResponse }
     * 
     */
    public GetTripsAreaTotalResponse createGetTripsAreaTotalResponse() {
        return new GetTripsAreaTotalResponse();
    }

    /**
     * Create an instance of {@link GetTripsCustom }
     * 
     */
    public GetTripsCustom createGetTripsCustom() {
        return new GetTripsCustom();
    }

    /**
     * Create an instance of {@link GetTripsCustomResponse }
     * 
     */
    public GetTripsCustomResponse createGetTripsCustomResponse() {
        return new GetTripsCustomResponse();
    }

    /**
     * Create an instance of {@link GetTripTables }
     * 
     */
    public GetTripTables createGetTripTables() {
        return new GetTripTables();
    }

    /**
     * Create an instance of {@link GetTripTablesResponse }
     * 
     */
    public GetTripTablesResponse createGetTripTablesResponse() {
        return new GetTripTablesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRTripTables }
     * 
     */
    public ArrayOfRTripTables createArrayOfRTripTables() {
        return new ArrayOfRTripTables();
    }

    /**
     * Create an instance of {@link ArrayOfRPropertyTareTableItem }
     * 
     */
    public ArrayOfRPropertyTareTableItem createArrayOfRPropertyTareTableItem() {
        return new ArrayOfRPropertyTareTableItem();
    }

    /**
     * Create an instance of {@link RPropertyTareTableItem }
     * 
     */
    public RPropertyTareTableItem createRPropertyTareTableItem() {
        return new RPropertyTareTableItem();
    }

    /**
     * Create an instance of {@link RRole }
     * 
     */
    public RRole createRRole() {
        return new RRole();
    }

    /**
     * Create an instance of {@link RUserRestriction }
     * 
     */
    public RUserRestriction createRUserRestriction() {
        return new RUserRestriction();
    }

    /**
     * Create an instance of {@link ArrayOfRGroupItem }
     * 
     */
    public ArrayOfRGroupItem createArrayOfRGroupItem() {
        return new ArrayOfRGroupItem();
    }

    /**
     * Create an instance of {@link RGroupItem }
     * 
     */
    public RGroupItem createRGroupItem() {
        return new RGroupItem();
    }

    /**
     * Create an instance of {@link RDeviceItem }
     * 
     */
    public RDeviceItem createRDeviceItem() {
        return new RDeviceItem();
    }

    /**
     * Create an instance of {@link ArrayOfRProperty }
     * 
     */
    public ArrayOfRProperty createArrayOfRProperty() {
        return new ArrayOfRProperty();
    }

    /**
     * Create an instance of {@link RProperty }
     * 
     */
    public RProperty createRProperty() {
        return new RProperty();
    }

    /**
     * Create an instance of {@link RPoint }
     * 
     */
    public RPoint createRPoint() {
        return new RPoint();
    }

    /**
     * Create an instance of {@link ArrayOfRTripSplitter }
     * 
     */
    public ArrayOfRTripSplitter createArrayOfRTripSplitter() {
        return new ArrayOfRTripSplitter();
    }

    /**
     * Create an instance of {@link RTripSplitter }
     * 
     */
    public RTripSplitter createRTripSplitter() {
        return new RTripSplitter();
    }

    /**
     * Create an instance of {@link ArrayOfRDeviceItem }
     * 
     */
    public ArrayOfRDeviceItem createArrayOfRDeviceItem() {
        return new ArrayOfRDeviceItem();
    }

    /**
     * Create an instance of {@link ArrayOfRDriverItem }
     * 
     */
    public ArrayOfRDriverItem createArrayOfRDriverItem() {
        return new ArrayOfRDriverItem();
    }

    /**
     * Create an instance of {@link RDriverItem }
     * 
     */
    public RDriverItem createRDriverItem() {
        return new RDriverItem();
    }

    /**
     * Create an instance of {@link ArrayOfRGeofenceItem }
     * 
     */
    public ArrayOfRGeofenceItem createArrayOfRGeofenceItem() {
        return new ArrayOfRGeofenceItem();
    }

    /**
     * Create an instance of {@link RGeofenceItem }
     * 
     */
    public RGeofenceItem createRGeofenceItem() {
        return new RGeofenceItem();
    }

    /**
     * Create an instance of {@link ArrayOfRImplementItem }
     * 
     */
    public ArrayOfRImplementItem createArrayOfRImplementItem() {
        return new ArrayOfRImplementItem();
    }

    /**
     * Create an instance of {@link RImplementItem }
     * 
     */
    public RImplementItem createRImplementItem() {
        return new RImplementItem();
    }

    /**
     * Create an instance of {@link RParameters }
     * 
     */
    public RParameters createRParameters() {
        return new RParameters();
    }

    /**
     * Create an instance of {@link ArrayOfRParameter }
     * 
     */
    public ArrayOfRParameter createArrayOfRParameter() {
        return new ArrayOfRParameter();
    }

    /**
     * Create an instance of {@link RParameter }
     * 
     */
    public RParameter createRParameter() {
        return new RParameter();
    }

    /**
     * Create an instance of {@link RBaseParameterValue }
     * 
     */
    public RBaseParameterValue createRBaseParameterValue() {
        return new RBaseParameterValue();
    }

    /**
     * Create an instance of {@link ArrayOfRParameterStatus }
     * 
     */
    public ArrayOfRParameterStatus createArrayOfRParameterStatus() {
        return new ArrayOfRParameterStatus();
    }

    /**
     * Create an instance of {@link RParameterStatus }
     * 
     */
    public RParameterStatus createRParameterStatus() {
        return new RParameterStatus();
    }

    /**
     * Create an instance of {@link RSchema }
     * 
     */
    public RSchema createRSchema() {
        return new RSchema();
    }

    /**
     * Create an instance of {@link RDeviceStatus }
     * 
     */
    public RDeviceStatus createRDeviceStatus() {
        return new RDeviceStatus();
    }

    /**
     * Create an instance of {@link RDataRange }
     * 
     */
    public RDataRange createRDataRange() {
        return new RDataRange();
    }

    /**
     * Create an instance of {@link ArrayOfRDataRangeItem }
     * 
     */
    public ArrayOfRDataRangeItem createArrayOfRDataRangeItem() {
        return new ArrayOfRDataRangeItem();
    }

    /**
     * Create an instance of {@link RDataRangeItem }
     * 
     */
    public RDataRangeItem createRDataRangeItem() {
        return new RDataRangeItem();
    }

    /**
     * Create an instance of {@link ArrayOfRDeviceStage }
     * 
     */
    public ArrayOfRDeviceStage createArrayOfRDeviceStage() {
        return new ArrayOfRDeviceStage();
    }

    /**
     * Create an instance of {@link RDeviceStage }
     * 
     */
    public RDeviceStage createRDeviceStage() {
        return new RDeviceStage();
    }

    /**
     * Create an instance of {@link RGeoFenceBase }
     * 
     */
    public RGeoFenceBase createRGeoFenceBase() {
        return new RGeoFenceBase();
    }

    /**
     * Create an instance of {@link ArrayOfDouble }
     * 
     */
    public ArrayOfDouble createArrayOfDouble() {
        return new ArrayOfDouble();
    }

    /**
     * Create an instance of {@link ArrayOfRGeoFenceHole }
     * 
     */
    public ArrayOfRGeoFenceHole createArrayOfRGeoFenceHole() {
        return new ArrayOfRGeoFenceHole();
    }

    /**
     * Create an instance of {@link RGeoFenceHole }
     * 
     */
    public RGeoFenceHole createRGeoFenceHole() {
        return new RGeoFenceHole();
    }

    /**
     * Create an instance of {@link RGeoFence }
     * 
     */
    public RGeoFence createRGeoFence() {
        return new RGeoFence();
    }

    /**
     * Create an instance of {@link ROnlineInfo1C }
     * 
     */
    public ROnlineInfo1C createROnlineInfo1C() {
        return new ROnlineInfo1C();
    }

    /**
     * Create an instance of {@link ArrayOfRObjectValue1C }
     * 
     */
    public ArrayOfRObjectValue1C createArrayOfRObjectValue1C() {
        return new ArrayOfRObjectValue1C();
    }

    /**
     * Create an instance of {@link RObjectValue1C }
     * 
     */
    public RObjectValue1C createRObjectValue1C() {
        return new RObjectValue1C();
    }

    /**
     * Create an instance of {@link RRouteSegment }
     * 
     */
    public RRouteSegment createRRouteSegment() {
        return new RRouteSegment();
    }

    /**
     * Create an instance of {@link TimeSpan }
     * 
     */
    public TimeSpan createTimeSpan() {
        return new TimeSpan();
    }

    /**
     * Create an instance of {@link RTripStage1C }
     * 
     */
    public RTripStage1C createRTripStage1C() {
        return new RTripStage1C();
    }

    /**
     * Create an instance of {@link ArrayOfReturnType }
     * 
     */
    public ArrayOfReturnType createArrayOfReturnType() {
        return new ArrayOfReturnType();
    }

    /**
     * Create an instance of {@link ArrayOfRTripStageItem }
     * 
     */
    public ArrayOfRTripStageItem createArrayOfRTripStageItem() {
        return new ArrayOfRTripStageItem();
    }

    /**
     * Create an instance of {@link RTripStageItem }
     * 
     */
    public RTripStageItem createRTripStageItem() {
        return new RTripStageItem();
    }

    /**
     * Create an instance of {@link ArrayOfAnyType }
     * 
     */
    public ArrayOfAnyType createArrayOfAnyType() {
        return new ArrayOfAnyType();
    }

    /**
     * Create an instance of {@link RTrackInfo1C }
     * 
     */
    public RTrackInfo1C createRTrackInfo1C() {
        return new RTrackInfo1C();
    }

    /**
     * Create an instance of {@link ArrayOfRTrackInfo }
     * 
     */
    public ArrayOfRTrackInfo createArrayOfRTrackInfo() {
        return new ArrayOfRTrackInfo();
    }

    /**
     * Create an instance of {@link RTrackInfo }
     * 
     */
    public RTrackInfo createRTrackInfo() {
        return new RTrackInfo();
    }

    /**
     * Create an instance of {@link ArrayOfDateTime }
     * 
     */
    public ArrayOfDateTime createArrayOfDateTime() {
        return new ArrayOfDateTime();
    }

    /**
     * Create an instance of {@link ArrayOfRTrackInfoPhoto }
     * 
     */
    public ArrayOfRTrackInfoPhoto createArrayOfRTrackInfoPhoto() {
        return new ArrayOfRTrackInfoPhoto();
    }

    /**
     * Create an instance of {@link RTrackInfoPhoto }
     * 
     */
    public RTrackInfoPhoto createRTrackInfoPhoto() {
        return new RTrackInfoPhoto();
    }

    /**
     * Create an instance of {@link RMonitoringRule1C }
     * 
     */
    public RMonitoringRule1C createRMonitoringRule1C() {
        return new RMonitoringRule1C();
    }

    /**
     * Create an instance of {@link ArrayOfMRuleStringPair1C }
     * 
     */
    public ArrayOfMRuleStringPair1C createArrayOfMRuleStringPair1C() {
        return new ArrayOfMRuleStringPair1C();
    }

    /**
     * Create an instance of {@link MRuleStringPair1C }
     * 
     */
    public MRuleStringPair1C createMRuleStringPair1C() {
        return new MRuleStringPair1C();
    }

    /**
     * Create an instance of {@link ArrayOfMRuleNotifyUser1C }
     * 
     */
    public ArrayOfMRuleNotifyUser1C createArrayOfMRuleNotifyUser1C() {
        return new ArrayOfMRuleNotifyUser1C();
    }

    /**
     * Create an instance of {@link MRuleNotifyUser1C }
     * 
     */
    public MRuleNotifyUser1C createMRuleNotifyUser1C() {
        return new MRuleNotifyUser1C();
    }

    /**
     * Create an instance of {@link ArrayOfMRuleNotifyTarget1C }
     * 
     */
    public ArrayOfMRuleNotifyTarget1C createArrayOfMRuleNotifyTarget1C() {
        return new ArrayOfMRuleNotifyTarget1C();
    }

    /**
     * Create an instance of {@link MRuleNotifyTarget1C }
     * 
     */
    public MRuleNotifyTarget1C createMRuleNotifyTarget1C() {
        return new MRuleNotifyTarget1C();
    }

    /**
     * Create an instance of {@link RMonitoringNotifyItem }
     * 
     */
    public RMonitoringNotifyItem createRMonitoringNotifyItem() {
        return new RMonitoringNotifyItem();
    }

    /**
     * Create an instance of {@link ArrayOfMRuleScheduleDay1C }
     * 
     */
    public ArrayOfMRuleScheduleDay1C createArrayOfMRuleScheduleDay1C() {
        return new ArrayOfMRuleScheduleDay1C();
    }

    /**
     * Create an instance of {@link MRuleScheduleDay1C }
     * 
     */
    public MRuleScheduleDay1C createMRuleScheduleDay1C() {
        return new MRuleScheduleDay1C();
    }

    /**
     * Create an instance of {@link RNote1C }
     * 
     */
    public RNote1C createRNote1C() {
        return new RNote1C();
    }

    /**
     * Create an instance of {@link ArrayOfRNote }
     * 
     */
    public ArrayOfRNote createArrayOfRNote() {
        return new ArrayOfRNote();
    }

    /**
     * Create an instance of {@link RNote }
     * 
     */
    public RNote createRNote() {
        return new RNote();
    }

    /**
     * Create an instance of {@link RProperties1C }
     * 
     */
    public RProperties1C createRProperties1C() {
        return new RProperties1C();
    }

    /**
     * Create an instance of {@link RPropertyItem1C }
     * 
     */
    public RPropertyItem1C createRPropertyItem1C() {
        return new RPropertyItem1C();
    }

    /**
     * Create an instance of {@link RPropertySetItem1C }
     * 
     */
    public RPropertySetItem1C createRPropertySetItem1C() {
        return new RPropertySetItem1C();
    }

    /**
     * Create an instance of {@link RReportScheduleItem }
     * 
     */
    public RReportScheduleItem createRReportScheduleItem() {
        return new RReportScheduleItem();
    }

    /**
     * Create an instance of {@link GetReportResult1C }
     * 
     */
    public GetReportResult1C createGetReportResult1C() {
        return new GetReportResult1C();
    }

    /**
     * Create an instance of {@link RTaskInfo }
     * 
     */
    public RTaskInfo createRTaskInfo() {
        return new RTaskInfo();
    }

    /**
     * Create an instance of {@link ArrayOfRTask }
     * 
     */
    public ArrayOfRTask createArrayOfRTask() {
        return new ArrayOfRTask();
    }

    /**
     * Create an instance of {@link RTask }
     * 
     */
    public RTask createRTask() {
        return new RTask();
    }

    /**
     * Create an instance of {@link ArrayOfRTaskGeofence }
     * 
     */
    public ArrayOfRTaskGeofence createArrayOfRTaskGeofence() {
        return new ArrayOfRTaskGeofence();
    }

    /**
     * Create an instance of {@link RTaskGeofence }
     * 
     */
    public RTaskGeofence createRTaskGeofence() {
        return new RTaskGeofence();
    }

    /**
     * Create an instance of {@link RTaskInfo1C }
     * 
     */
    public RTaskInfo1C createRTaskInfo1C() {
        return new RTaskInfo1C();
    }

    /**
     * Create an instance of {@link RTripItemContainer }
     * 
     */
    public RTripItemContainer createRTripItemContainer() {
        return new RTripItemContainer();
    }

    /**
     * Create an instance of {@link ArrayOfRTripItem }
     * 
     */
    public ArrayOfRTripItem createArrayOfRTripItem() {
        return new ArrayOfRTripItem();
    }

    /**
     * Create an instance of {@link RTripItem }
     * 
     */
    public RTripItem createRTripItem() {
        return new RTripItem();
    }

    /**
     * Create an instance of {@link RTrips1C }
     * 
     */
    public RTrips1C createRTrips1C() {
        return new RTrips1C();
    }

    /**
     * Create an instance of {@link ArrayOfRTrip1C }
     * 
     */
    public ArrayOfRTrip1C createArrayOfRTrip1C() {
        return new ArrayOfRTrip1C();
    }

    /**
     * Create an instance of {@link RTrip1C }
     * 
     */
    public RTrip1C createRTrip1C() {
        return new RTrip1C();
    }

    /**
     * Create an instance of {@link ArrayOfRTripArea }
     * 
     */
    public ArrayOfRTripArea createArrayOfRTripArea() {
        return new ArrayOfRTripArea();
    }

    /**
     * Create an instance of {@link RTripArea }
     * 
     */
    public RTripArea createRTripArea() {
        return new RTripArea();
    }

    /**
     * Create an instance of {@link ArrayOfArrayOfArrayOfDouble }
     * 
     */
    public ArrayOfArrayOfArrayOfDouble createArrayOfArrayOfArrayOfDouble() {
        return new ArrayOfArrayOfArrayOfDouble();
    }

    /**
     * Create an instance of {@link ArrayOfArrayOfDouble }
     * 
     */
    public ArrayOfArrayOfDouble createArrayOfArrayOfDouble() {
        return new ArrayOfArrayOfDouble();
    }

    /**
     * Create an instance of {@link RTripRequest }
     * 
     */
    public RTripRequest createRTripRequest() {
        return new RTripRequest();
    }

    /**
     * Create an instance of {@link RTripTables }
     * 
     */
    public RTripTables createRTripTables() {
        return new RTripTables();
    }

    /**
     * Create an instance of {@link ArrayOfRTripTableItem }
     * 
     */
    public ArrayOfRTripTableItem createArrayOfRTripTableItem() {
        return new ArrayOfRTripTableItem();
    }

    /**
     * Create an instance of {@link RTripTableItem }
     * 
     */
    public RTripTableItem createRTripTableItem() {
        return new RTripTableItem();
    }

    /**
     * Create an instance of {@link ArrayOfRTripTableValues }
     * 
     */
    public ArrayOfRTripTableValues createArrayOfRTripTableValues() {
        return new ArrayOfRTripTableValues();
    }

    /**
     * Create an instance of {@link RTripTableValues }
     * 
     */
    public RTripTableValues createRTripTableValues() {
        return new RTripTableValues();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_SD", scope = RTrip1C.class)
    public JAXBElement<XMLGregorianCalendar> createRTrip1CSD1(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RTrip1CSD1_QNAME, XMLGregorianCalendar.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_ED", scope = RTrip1C.class)
    public JAXBElement<XMLGregorianCalendar> createRTrip1CED1(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RTrip1CED1_QNAME, XMLGregorianCalendar.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Index", scope = RTrip1C.class)
    public JAXBElement<Integer> createRTrip1CIndex(Integer value) {
        return new JAXBElement<Integer>(_RTrip1CIndex_QNAME, Integer.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "SD", scope = RTrip1C.class)
    public JAXBElement<Object> createRTrip1CED2(Object value) {
        return new JAXBElement<Object>(_RTrip1CED2_QNAME, Object.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ED", scope = RTrip1C.class)
    public JAXBElement<Object> createRTrip1CEE2(Object value) {
        return new JAXBElement<Object>(_RTrip1CEE2_QNAME, Object.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "PointStart", scope = RTrip1C.class)
    public JAXBElement<RPoint> createRTrip1CPointStart(RPoint value) {
        return new JAXBElement<RPoint>(_RTrip1CPointStart_QNAME, RPoint.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "PointEnd", scope = RTrip1C.class)
    public JAXBElement<RPoint> createRTrip1CPointEnd(RPoint value) {
        return new JAXBElement<RPoint>(_RTrip1CPointEnd_QNAME, RPoint.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRTripStage1C }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfRTripStage1C }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Stages", scope = RTrip1C.class)
    public JAXBElement<ArrayOfRTripStage1C> createRTrip1CStages(ArrayOfRTripStage1C value) {
        return new JAXBElement<ArrayOfRTripStage1C>(_RTrip1CStages_QNAME, ArrayOfRTripStage1C.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRObjectValue1C }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfRObjectValue1C }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Total", scope = RTrip1C.class)
    public JAXBElement<ArrayOfRObjectValue1C> createRTrip1CTotal(ArrayOfRObjectValue1C value) {
        return new JAXBElement<ArrayOfRObjectValue1C>(_RTrip1CTotal_QNAME, ArrayOfRObjectValue1C.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRTripArea }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfRTripArea }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Areas", scope = RTrip1C.class)
    public JAXBElement<ArrayOfRTripArea> createRTrip1CAreas(ArrayOfRTripArea value) {
        return new JAXBElement<ArrayOfRTripArea>(_RTrip1CAreas_QNAME, ArrayOfRTripArea.class, RTrip1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_LastCoords", scope = RTrips1C.class)
    public JAXBElement<XMLGregorianCalendar> createLastCoords1(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastCoords1_QNAME, XMLGregorianCalendar.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_LastData", scope = RTrips1C.class)
    public JAXBElement<XMLGregorianCalendar> createLastData1(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastData1_QNAME, XMLGregorianCalendar.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ID", scope = RTrips1C.class)
    public JAXBElement<String> createRTrips1CID(String value) {
        return new JAXBElement<String>(_RTrips1CID_QNAME, String.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Name", scope = RTrips1C.class)
    public JAXBElement<String> createRTrips1CName(String value) {
        return new JAXBElement<String>(_RTrips1CName_QNAME, String.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Serial", scope = RTrips1C.class)
    public JAXBElement<Integer> createRTrips1CSerial(Integer value) {
        return new JAXBElement<Integer>(_RTrips1CSerial_QNAME, Integer.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "VRN", scope = RTrips1C.class)
    public JAXBElement<String> createRTrips1CVRN(String value) {
        return new JAXBElement<String>(_RTrips1CVRN_QNAME, String.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRTrip1C }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfRTrip1C }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Trips", scope = RTrips1C.class)
    public JAXBElement<ArrayOfRTrip1C> createRTrips1CTrips(ArrayOfRTrip1C value) {
        return new JAXBElement<ArrayOfRTrip1C>(_RTrips1CTrips_QNAME, ArrayOfRTrip1C.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRObjectValue1C }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfRObjectValue1C }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Total", scope = RTrips1C.class)
    public JAXBElement<ArrayOfRObjectValue1C> createRTrips1CTotal(ArrayOfRObjectValue1C value) {
        return new JAXBElement<ArrayOfRObjectValue1C>(_RTrip1CTotal_QNAME, ArrayOfRObjectValue1C.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "LastPosition", scope = RTrips1C.class)
    public JAXBElement<RPoint> createRTrips1CLastPosition(RPoint value) {
        return new JAXBElement<RPoint>(_RTrips1CLastPosition_QNAME, RPoint.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "LastCoords", scope = RTrips1C.class)
    public JAXBElement<Object> createRTrips1CLastCoords(Object value) {
        return new JAXBElement<Object>(_RTrips1CLastCoords_QNAME, Object.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "LastData", scope = RTrips1C.class)
    public JAXBElement<Object> createRTrips1CLastData(Object value) {
        return new JAXBElement<Object>(_RTrips1CLastData_QNAME, Object.class, RTrips1C.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_SD", scope = RTripStageItem.class)
    public JAXBElement<XMLGregorianCalendar> createRTripStageItemSD1(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RTrip1CSD1_QNAME, XMLGregorianCalendar.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_ED", scope = RTripStageItem.class)
    public JAXBElement<XMLGregorianCalendar> createRTripStageItemED1(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RTrip1CED1_QNAME, XMLGregorianCalendar.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Index", scope = RTripStageItem.class)
    public JAXBElement<Integer> createRTripStageItemIndex(Integer value) {
        return new JAXBElement<Integer>(_RTrip1CIndex_QNAME, Integer.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "SD", scope = RTripStageItem.class)
    public JAXBElement<Object> createRTripStageItemSD2(Object value) {
        return new JAXBElement<Object>(_RTrip1CED2_QNAME, Object.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ED", scope = RTripStageItem.class)
    public JAXBElement<Object> createRTripStageItemED2(Object value) {
        return new JAXBElement<Object>(_RTrip1CEE2_QNAME, Object.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Status", scope = RTripStageItem.class)
    public JAXBElement<Integer> createRTripStageItemStatus(Integer value) {
        return new JAXBElement<Integer>(_RTripStageItemStatus_QNAME, Integer.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "StatusID", scope = RTripStageItem.class)
    public JAXBElement<String> createRTripStageItemStatusID(String value) {
        return new JAXBElement<String>(_RTripStageItemStatusID_QNAME, String.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfGuid }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfGuid }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "StatusIDs", scope = RTripStageItem.class)
    public JAXBElement<ArrayOfGuid> createRTripStageItemStatusIDs(ArrayOfGuid value) {
        return new JAXBElement<ArrayOfGuid>(_RTripStageItemStatusIDs_QNAME, ArrayOfGuid.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "StartPoint", scope = RTripStageItem.class)
    public JAXBElement<RPoint> createRTripStageItemStartPoint(RPoint value) {
        return new JAXBElement<RPoint>(_RTripStageItemStartPoint_QNAME, RPoint.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RPoint }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "EndPoint", scope = RTripStageItem.class)
    public JAXBElement<RPoint> createRTripStageItemEndPoint(RPoint value) {
        return new JAXBElement<RPoint>(_RTripStageItemEndPoint_QNAME, RPoint.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Caption", scope = RTripStageItem.class)
    public JAXBElement<String> createRTripStageItemCaption(String value) {
        return new JAXBElement<String>(_RTripStageItemCaption_QNAME, String.class, RTripStageItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfAnyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfAnyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "Values", scope = RTripStageItem.class)
    public JAXBElement<ArrayOfAnyType> createRTripStageItemValues(ArrayOfAnyType value) {
        return new JAXBElement<ArrayOfAnyType>(_RTripStageItemValues_QNAME, ArrayOfAnyType.class, RTripStageItem.class, value);
    }

}
