//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="schemaID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IDUSER" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="carOrGroupID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="objectSubgroups" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="showTrack" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="showStages" type="{http://tempuri.org/}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="geoOrGroupFilterID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="geoFilterSubgroups" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="geoOrGroupShowID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="geoShowSubgroups" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="geoShowIcons" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="geoShowLabels" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="SD" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ED" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ViewSD" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ViewED" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schemaID",
    "iduser",
    "carOrGroupID",
    "objectSubgroups",
    "showTrack",
    "showStages",
    "geoOrGroupFilterID",
    "geoFilterSubgroups",
    "geoOrGroupShowID",
    "geoShowSubgroups",
    "geoShowIcons",
    "geoShowLabels",
    "sd",
    "ed",
    "viewSD",
    "viewED"
})
@XmlRootElement(name = "OTLCreate")
public class OTLCreate {

    protected String schemaID;
    @XmlElement(name = "IDUSER", required = true)
    protected String iduser;
    @XmlElement(required = true)
    protected String carOrGroupID;
    protected boolean objectSubgroups;
    protected boolean showTrack;
    protected ArrayOfString showStages;
    @XmlElement(required = true, nillable = true)
    protected String geoOrGroupFilterID;
    protected boolean geoFilterSubgroups;
    @XmlElement(required = true, nillable = true)
    protected String geoOrGroupShowID;
    protected boolean geoShowSubgroups;
    protected boolean geoShowIcons;
    protected boolean geoShowLabels;
    @XmlElement(name = "SD", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sd;
    @XmlElement(name = "ED", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ed;
    @XmlElement(name = "ViewSD", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar viewSD;
    @XmlElement(name = "ViewED", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar viewED;

    /**
     * Gets the value of the schemaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaID() {
        return schemaID;
    }

    /**
     * Sets the value of the schemaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaID(String value) {
        this.schemaID = value;
    }

    /**
     * Gets the value of the iduser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDUSER() {
        return iduser;
    }

    /**
     * Sets the value of the iduser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDUSER(String value) {
        this.iduser = value;
    }

    /**
     * Gets the value of the carOrGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarOrGroupID() {
        return carOrGroupID;
    }

    /**
     * Sets the value of the carOrGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarOrGroupID(String value) {
        this.carOrGroupID = value;
    }

    /**
     * Gets the value of the objectSubgroups property.
     * 
     */
    public boolean isObjectSubgroups() {
        return objectSubgroups;
    }

    /**
     * Sets the value of the objectSubgroups property.
     * 
     */
    public void setObjectSubgroups(boolean value) {
        this.objectSubgroups = value;
    }

    /**
     * Gets the value of the showTrack property.
     * 
     */
    public boolean isShowTrack() {
        return showTrack;
    }

    /**
     * Sets the value of the showTrack property.
     * 
     */
    public void setShowTrack(boolean value) {
        this.showTrack = value;
    }

    /**
     * Gets the value of the showStages property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getShowStages() {
        return showStages;
    }

    /**
     * Sets the value of the showStages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setShowStages(ArrayOfString value) {
        this.showStages = value;
    }

    /**
     * Gets the value of the geoOrGroupFilterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoOrGroupFilterID() {
        return geoOrGroupFilterID;
    }

    /**
     * Sets the value of the geoOrGroupFilterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoOrGroupFilterID(String value) {
        this.geoOrGroupFilterID = value;
    }

    /**
     * Gets the value of the geoFilterSubgroups property.
     * 
     */
    public boolean isGeoFilterSubgroups() {
        return geoFilterSubgroups;
    }

    /**
     * Sets the value of the geoFilterSubgroups property.
     * 
     */
    public void setGeoFilterSubgroups(boolean value) {
        this.geoFilterSubgroups = value;
    }

    /**
     * Gets the value of the geoOrGroupShowID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoOrGroupShowID() {
        return geoOrGroupShowID;
    }

    /**
     * Sets the value of the geoOrGroupShowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoOrGroupShowID(String value) {
        this.geoOrGroupShowID = value;
    }

    /**
     * Gets the value of the geoShowSubgroups property.
     * 
     */
    public boolean isGeoShowSubgroups() {
        return geoShowSubgroups;
    }

    /**
     * Sets the value of the geoShowSubgroups property.
     * 
     */
    public void setGeoShowSubgroups(boolean value) {
        this.geoShowSubgroups = value;
    }

    /**
     * Gets the value of the geoShowIcons property.
     * 
     */
    public boolean isGeoShowIcons() {
        return geoShowIcons;
    }

    /**
     * Sets the value of the geoShowIcons property.
     * 
     */
    public void setGeoShowIcons(boolean value) {
        this.geoShowIcons = value;
    }

    /**
     * Gets the value of the geoShowLabels property.
     * 
     */
    public boolean isGeoShowLabels() {
        return geoShowLabels;
    }

    /**
     * Sets the value of the geoShowLabels property.
     * 
     */
    public void setGeoShowLabels(boolean value) {
        this.geoShowLabels = value;
    }

    /**
     * Gets the value of the sd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSD() {
        return sd;
    }

    /**
     * Sets the value of the sd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSD(XMLGregorianCalendar value) {
        this.sd = value;
    }

    /**
     * Gets the value of the ed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getED() {
        return ed;
    }

    /**
     * Sets the value of the ed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setED(XMLGregorianCalendar value) {
        this.ed = value;
    }

    /**
     * Gets the value of the viewSD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getViewSD() {
        return viewSD;
    }

    /**
     * Sets the value of the viewSD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setViewSD(XMLGregorianCalendar value) {
        this.viewSD = value;
    }

    /**
     * Gets the value of the viewED property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getViewED() {
        return viewED;
    }

    /**
     * Sets the value of the viewED property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setViewED(XMLGregorianCalendar value) {
        this.viewED = value;
    }

}
