//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportFormat.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReportFormat"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PDF"/&gt;
 *     &lt;enumeration value="Excel2007"/&gt;
 *     &lt;enumeration value="Word2007"/&gt;
 *     &lt;enumeration value="RTF"/&gt;
 *     &lt;enumeration value="XPS"/&gt;
 *     &lt;enumeration value="ODS"/&gt;
 *     &lt;enumeration value="ODT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ReportFormat")
@XmlEnum
public enum ReportFormat {

    PDF("PDF"),
    @XmlEnumValue("Excel2007")
    EXCEL_2007("Excel2007"),
    @XmlEnumValue("Word2007")
    WORD_2007("Word2007"),
    RTF("RTF"),
    XPS("XPS"),
    ODS("ODS"),
    ODT("ODT");
    private final String value;

    ReportFormat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReportFormat fromValue(String v) {
        for (ReportFormat c: ReportFormat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
