//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReturnType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Boolean"/&gt;
 *     &lt;enumeration value="Byte"/&gt;
 *     &lt;enumeration value="Int32"/&gt;
 *     &lt;enumeration value="Int64"/&gt;
 *     &lt;enumeration value="Double"/&gt;
 *     &lt;enumeration value="DateTime"/&gt;
 *     &lt;enumeration value="TimeSpan"/&gt;
 *     &lt;enumeration value="Guid"/&gt;
 *     &lt;enumeration value="Guid4"/&gt;
 *     &lt;enumeration value="String"/&gt;
 *     &lt;enumeration value="Image"/&gt;
 *     &lt;enumeration value="Coordinates"/&gt;
 *     &lt;enumeration value="Location"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ReturnType")
@XmlEnum
public enum ReturnType {

    @XmlEnumValue("Boolean")
    BOOLEAN("Boolean"),
    @XmlEnumValue("Byte")
    BYTE("Byte"),
    @XmlEnumValue("Int32")
    INT_32("Int32"),
    @XmlEnumValue("Int64")
    INT_64("Int64"),
    @XmlEnumValue("Double")
    DOUBLE("Double"),
    @XmlEnumValue("DateTime")
    DATE_TIME("DateTime"),
    @XmlEnumValue("TimeSpan")
    TIME_SPAN("TimeSpan"),
    @XmlEnumValue("Guid")
    GUID("Guid"),
    @XmlEnumValue("Guid4")
    GUID_4("Guid4"),
    @XmlEnumValue("String")
    STRING("String"),
    @XmlEnumValue("Image")
    IMAGE("Image"),
    @XmlEnumValue("Coordinates")
    COORDINATES("Coordinates"),
    @XmlEnumValue("Location")
    LOCATION("Location");
    private final String value;

    ReturnType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReturnType fromValue(String v) {
        for (ReturnType c: ReturnType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
