//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RGeoFenceBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RGeoFenceBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="ParentID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsPolygon" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Lat" type="{http://tempuri.org/}ArrayOfDouble" minOccurs="0"/&gt;
 *         &lt;element name="Lng" type="{http://tempuri.org/}ArrayOfDouble" minOccurs="0"/&gt;
 *         &lt;element name="Holes" type="{http://tempuri.org/}ArrayOfRGeoFenceHole" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RGeoFenceBase", propOrder = {
    "id",
    "parentID",
    "name",
    "isPolygon",
    "r",
    "lat",
    "lng",
    "holes"
})
@XmlSeeAlso({
    RGeoFence.class
})
public class RGeoFenceBase {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "ParentID", required = true, nillable = true)
    protected String parentID;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "IsPolygon")
    protected boolean isPolygon;
    @XmlElement(name = "R")
    protected double r;
    @XmlElement(name = "Lat")
    protected ArrayOfDouble lat;
    @XmlElement(name = "Lng")
    protected ArrayOfDouble lng;
    @XmlElement(name = "Holes")
    protected ArrayOfRGeoFenceHole holes;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentID(String value) {
        this.parentID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isPolygon property.
     * 
     */
    public boolean isIsPolygon() {
        return isPolygon;
    }

    /**
     * Sets the value of the isPolygon property.
     * 
     */
    public void setIsPolygon(boolean value) {
        this.isPolygon = value;
    }

    /**
     * Gets the value of the r property.
     * 
     */
    public double getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     */
    public void setR(double value) {
        this.r = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDouble }
     *     
     */
    public ArrayOfDouble getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDouble }
     *     
     */
    public void setLat(ArrayOfDouble value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lng property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDouble }
     *     
     */
    public ArrayOfDouble getLng() {
        return lng;
    }

    /**
     * Sets the value of the lng property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDouble }
     *     
     */
    public void setLng(ArrayOfDouble value) {
        this.lng = value;
    }

    /**
     * Gets the value of the holes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRGeoFenceHole }
     *     
     */
    public ArrayOfRGeoFenceHole getHoles() {
        return holes;
    }

    /**
     * Sets the value of the holes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRGeoFenceHole }
     *     
     */
    public void setHoles(ArrayOfRGeoFenceHole value) {
        this.holes = value;
    }

}
