//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RGeoFence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RGeoFence"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}RGeoFenceBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ImageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ImageHue" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Fill" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RGeoFence", propOrder = {
    "imageName",
    "imageHue",
    "fill",
    "line",
    "lineWidth"
})
public class RGeoFence
    extends RGeoFenceBase
{

    @XmlElement(name = "ImageName")
    protected String imageName;
    @XmlElement(name = "ImageHue")
    protected int imageHue;
    @XmlElement(name = "Fill")
    protected int fill;
    @XmlElement(name = "Line")
    protected int line;
    @XmlElement(name = "LineWidth")
    protected int lineWidth;

    /**
     * Gets the value of the imageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * Sets the value of the imageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageName(String value) {
        this.imageName = value;
    }

    /**
     * Gets the value of the imageHue property.
     * 
     */
    public int getImageHue() {
        return imageHue;
    }

    /**
     * Sets the value of the imageHue property.
     * 
     */
    public void setImageHue(int value) {
        this.imageHue = value;
    }

    /**
     * Gets the value of the fill property.
     * 
     */
    public int getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     */
    public void setFill(int value) {
        this.fill = value;
    }

    /**
     * Gets the value of the line property.
     * 
     */
    public int getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     */
    public void setLine(int value) {
        this.line = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     */
    public int getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     */
    public void setLineWidth(int value) {
        this.lineWidth = value;
    }

}
