//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RMonitoringRule1C complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RMonitoringRule1C"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Parameter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ParameterType" type="{http://tempuri.org/}RParameterType"/&gt;
 *         &lt;element name="Condition" type="{http://tempuri.org/}RMonitoringRuleCondition"/&gt;
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ValueType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ValueTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ValueToType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TargetObject" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="IgnorePeriod" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="MinDuration" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Templates" type="{http://tempuri.org/}ArrayOfMRuleStringPair1C" minOccurs="0"/&gt;
 *         &lt;element name="Subjects" type="{http://tempuri.org/}ArrayOfMRuleStringPair1C" minOccurs="0"/&gt;
 *         &lt;element name="PutToJournal" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ChangeStateRuleID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="ChangeStateRuleTo" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="NotifyUsers" type="{http://tempuri.org/}ArrayOfMRuleNotifyUser1C" minOccurs="0"/&gt;
 *         &lt;element name="NotifyTargets" type="{http://tempuri.org/}ArrayOfMRuleNotifyTarget1C" minOccurs="0"/&gt;
 *         &lt;element name="Schedule" type="{http://tempuri.org/}ArrayOfMRuleScheduleDay1C" minOccurs="0"/&gt;
 *         &lt;element name="Created" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Updated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RMonitoringRule1C", propOrder = {
    "id",
    "parameter",
    "parameterType",
    "condition",
    "value",
    "valueType",
    "valueTo",
    "valueToType",
    "targetObject",
    "state",
    "severity",
    "ignorePeriod",
    "minDuration",
    "templates",
    "subjects",
    "putToJournal",
    "changeStateRuleID",
    "changeStateRuleTo",
    "notifyUsers",
    "notifyTargets",
    "schedule",
    "created",
    "updated"
})
public class RMonitoringRule1C {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Parameter")
    protected String parameter;
    @XmlElement(name = "ParameterType", required = true)
    @XmlSchemaType(name = "string")
    protected RParameterType parameterType;
    @XmlElement(name = "Condition", required = true)
    @XmlSchemaType(name = "string")
    protected RMonitoringRuleCondition condition;
    @XmlElement(name = "Value")
    protected String value;
    @XmlElement(name = "ValueType")
    protected String valueType;
    @XmlElement(name = "ValueTo")
    protected String valueTo;
    @XmlElement(name = "ValueToType")
    protected String valueToType;
    @XmlElement(name = "TargetObject", required = true)
    protected String targetObject;
    @XmlElement(name = "State")
    protected boolean state;
    @XmlElement(name = "Severity")
    protected int severity;
    @XmlElement(name = "IgnorePeriod")
    protected int ignorePeriod;
    @XmlElement(name = "MinDuration")
    protected int minDuration;
    @XmlElement(name = "Templates")
    protected ArrayOfMRuleStringPair1C templates;
    @XmlElement(name = "Subjects")
    protected ArrayOfMRuleStringPair1C subjects;
    @XmlElement(name = "PutToJournal")
    protected boolean putToJournal;
    @XmlElement(name = "ChangeStateRuleID", required = true, nillable = true)
    protected String changeStateRuleID;
    @XmlElement(name = "ChangeStateRuleTo", required = true, type = Boolean.class, nillable = true)
    protected Boolean changeStateRuleTo;
    @XmlElement(name = "NotifyUsers")
    protected ArrayOfMRuleNotifyUser1C notifyUsers;
    @XmlElement(name = "NotifyTargets")
    protected ArrayOfMRuleNotifyTarget1C notifyTargets;
    @XmlElement(name = "Schedule")
    protected ArrayOfMRuleScheduleDay1C schedule;
    @XmlElement(name = "Created", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar created;
    @XmlElement(name = "Updated", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updated;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameter(String value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the parameterType property.
     * 
     * @return
     *     possible object is
     *     {@link RParameterType }
     *     
     */
    public RParameterType getParameterType() {
        return parameterType;
    }

    /**
     * Sets the value of the parameterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RParameterType }
     *     
     */
    public void setParameterType(RParameterType value) {
        this.parameterType = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link RMonitoringRuleCondition }
     *     
     */
    public RMonitoringRuleCondition getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMonitoringRuleCondition }
     *     
     */
    public void setCondition(RMonitoringRuleCondition value) {
        this.condition = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueType(String value) {
        this.valueType = value;
    }

    /**
     * Gets the value of the valueTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueTo() {
        return valueTo;
    }

    /**
     * Sets the value of the valueTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueTo(String value) {
        this.valueTo = value;
    }

    /**
     * Gets the value of the valueToType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueToType() {
        return valueToType;
    }

    /**
     * Sets the value of the valueToType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueToType(String value) {
        this.valueToType = value;
    }

    /**
     * Gets the value of the targetObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetObject() {
        return targetObject;
    }

    /**
     * Sets the value of the targetObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetObject(String value) {
        this.targetObject = value;
    }

    /**
     * Gets the value of the state property.
     * 
     */
    public boolean isState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     */
    public void setState(boolean value) {
        this.state = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     */
    public int getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     */
    public void setSeverity(int value) {
        this.severity = value;
    }

    /**
     * Gets the value of the ignorePeriod property.
     * 
     */
    public int getIgnorePeriod() {
        return ignorePeriod;
    }

    /**
     * Sets the value of the ignorePeriod property.
     * 
     */
    public void setIgnorePeriod(int value) {
        this.ignorePeriod = value;
    }

    /**
     * Gets the value of the minDuration property.
     * 
     */
    public int getMinDuration() {
        return minDuration;
    }

    /**
     * Sets the value of the minDuration property.
     * 
     */
    public void setMinDuration(int value) {
        this.minDuration = value;
    }

    /**
     * Gets the value of the templates property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMRuleStringPair1C }
     *     
     */
    public ArrayOfMRuleStringPair1C getTemplates() {
        return templates;
    }

    /**
     * Sets the value of the templates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMRuleStringPair1C }
     *     
     */
    public void setTemplates(ArrayOfMRuleStringPair1C value) {
        this.templates = value;
    }

    /**
     * Gets the value of the subjects property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMRuleStringPair1C }
     *     
     */
    public ArrayOfMRuleStringPair1C getSubjects() {
        return subjects;
    }

    /**
     * Sets the value of the subjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMRuleStringPair1C }
     *     
     */
    public void setSubjects(ArrayOfMRuleStringPair1C value) {
        this.subjects = value;
    }

    /**
     * Gets the value of the putToJournal property.
     * 
     */
    public boolean isPutToJournal() {
        return putToJournal;
    }

    /**
     * Sets the value of the putToJournal property.
     * 
     */
    public void setPutToJournal(boolean value) {
        this.putToJournal = value;
    }

    /**
     * Gets the value of the changeStateRuleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeStateRuleID() {
        return changeStateRuleID;
    }

    /**
     * Sets the value of the changeStateRuleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeStateRuleID(String value) {
        this.changeStateRuleID = value;
    }

    /**
     * Gets the value of the changeStateRuleTo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangeStateRuleTo() {
        return changeStateRuleTo;
    }

    /**
     * Sets the value of the changeStateRuleTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeStateRuleTo(Boolean value) {
        this.changeStateRuleTo = value;
    }

    /**
     * Gets the value of the notifyUsers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMRuleNotifyUser1C }
     *     
     */
    public ArrayOfMRuleNotifyUser1C getNotifyUsers() {
        return notifyUsers;
    }

    /**
     * Sets the value of the notifyUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMRuleNotifyUser1C }
     *     
     */
    public void setNotifyUsers(ArrayOfMRuleNotifyUser1C value) {
        this.notifyUsers = value;
    }

    /**
     * Gets the value of the notifyTargets property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMRuleNotifyTarget1C }
     *     
     */
    public ArrayOfMRuleNotifyTarget1C getNotifyTargets() {
        return notifyTargets;
    }

    /**
     * Sets the value of the notifyTargets property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMRuleNotifyTarget1C }
     *     
     */
    public void setNotifyTargets(ArrayOfMRuleNotifyTarget1C value) {
        this.notifyTargets = value;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMRuleScheduleDay1C }
     *     
     */
    public ArrayOfMRuleScheduleDay1C getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMRuleScheduleDay1C }
     *     
     */
    public void setSchedule(ArrayOfMRuleScheduleDay1C value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreated(XMLGregorianCalendar value) {
        this.created = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdated(XMLGregorianCalendar value) {
        this.updated = value;
    }

}
