//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ROnlineInfo1C complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ROnlineInfo1C"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastPosition" type="{http://tempuri.org/}RPoint" minOccurs="0"/&gt;
 *         &lt;element name="DT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="State" type="{http://tempuri.org/}ROnlineState"/&gt;
 *         &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Course" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Final" type="{http://tempuri.org/}ArrayOfRObjectValue1C" minOccurs="0"/&gt;
 *         &lt;element name="LastCoords" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ROnlineInfo1C", propOrder = {
    "id",
    "name",
    "lastPosition",
    "dt",
    "state",
    "speed",
    "course",
    "address",
    "_final",
    "lastCoords"
})
public class ROnlineInfo1C {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "LastPosition")
    protected RPoint lastPosition;
    @XmlElement(name = "DT", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dt;
    @XmlElement(name = "State", required = true)
    @XmlSchemaType(name = "string")
    protected ROnlineState state;
    @XmlElement(name = "Speed")
    protected double speed;
    @XmlElement(name = "Course")
    protected double course;
    @XmlElement(name = "Address")
    protected String address;
    @XmlElement(name = "Final")
    protected ArrayOfRObjectValue1C _final;
    @XmlElement(name = "LastCoords")
    protected Object lastCoords;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastPosition property.
     * 
     * @return
     *     possible object is
     *     {@link RPoint }
     *     
     */
    public RPoint getLastPosition() {
        return lastPosition;
    }

    /**
     * Sets the value of the lastPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link RPoint }
     *     
     */
    public void setLastPosition(RPoint value) {
        this.lastPosition = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDT() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDT(XMLGregorianCalendar value) {
        this.dt = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link ROnlineState }
     *     
     */
    public ROnlineState getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROnlineState }
     *     
     */
    public void setState(ROnlineState value) {
        this.state = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     */
    public double getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     */
    public void setSpeed(double value) {
        this.speed = value;
    }

    /**
     * Gets the value of the course property.
     * 
     */
    public double getCourse() {
        return course;
    }

    /**
     * Sets the value of the course property.
     * 
     */
    public void setCourse(double value) {
        this.course = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the final property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRObjectValue1C }
     *     
     */
    public ArrayOfRObjectValue1C getFinal() {
        return _final;
    }

    /**
     * Sets the value of the final property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRObjectValue1C }
     *     
     */
    public void setFinal(ArrayOfRObjectValue1C value) {
        this._final = value;
    }

    /**
     * Gets the value of the lastCoords property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLastCoords() {
        return lastCoords;
    }

    /**
     * Sets the value of the lastCoords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLastCoords(Object value) {
        this.lastCoords = value;
    }

}
