//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ROnlineState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ROnlineState"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Park"/&gt;
 *     &lt;enumeration value="Move"/&gt;
 *     &lt;enumeration value="Flight"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ROnlineState")
@XmlEnum
public enum ROnlineState {

    @XmlEnumValue("Park")
    PARK("Park"),
    @XmlEnumValue("Move")
    MOVE("Move"),
    @XmlEnumValue("Flight")
    FLIGHT("Flight");
    private final String value;

    ROnlineState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ROnlineState fromValue(String v) {
        for (ROnlineState c: ROnlineState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
