//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouterType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RouterType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Google"/&gt;
 *     &lt;enumeration value="Progorod"/&gt;
 *     &lt;enumeration value="GraphHopper"/&gt;
 *     &lt;enumeration value="OSRM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RouterType")
@XmlEnum
public enum RouterType {

    @XmlEnumValue("Google")
    GOOGLE("Google"),
    @XmlEnumValue("Progorod")
    PROGOROD("Progorod"),
    @XmlEnumValue("GraphHopper")
    GRAPH_HOPPER("GraphHopper"),
    OSRM("OSRM");
    private final String value;

    RouterType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RouterType fromValue(String v) {
        for (RouterType c: RouterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
