//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FinalParams" type="{http://tempuri.org/}ArrayOfRParameter" minOccurs="0"/&gt;
 *         &lt;element name="OnlineParams" type="{http://tempuri.org/}ArrayOfRParameter" minOccurs="0"/&gt;
 *         &lt;element name="TripsParams" type="{http://tempuri.org/}ArrayOfRParameter" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RParameters", propOrder = {
    "id",
    "name",
    "finalParams",
    "onlineParams",
    "tripsParams"
})
public class RParameters {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "FinalParams")
    protected ArrayOfRParameter finalParams;
    @XmlElement(name = "OnlineParams")
    protected ArrayOfRParameter onlineParams;
    @XmlElement(name = "TripsParams")
    protected ArrayOfRParameter tripsParams;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the finalParams property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRParameter }
     *     
     */
    public ArrayOfRParameter getFinalParams() {
        return finalParams;
    }

    /**
     * Sets the value of the finalParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRParameter }
     *     
     */
    public void setFinalParams(ArrayOfRParameter value) {
        this.finalParams = value;
    }

    /**
     * Gets the value of the onlineParams property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRParameter }
     *     
     */
    public ArrayOfRParameter getOnlineParams() {
        return onlineParams;
    }

    /**
     * Sets the value of the onlineParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRParameter }
     *     
     */
    public void setOnlineParams(ArrayOfRParameter value) {
        this.onlineParams = value;
    }

    /**
     * Gets the value of the tripsParams property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRParameter }
     *     
     */
    public ArrayOfRParameter getTripsParams() {
        return tripsParams;
    }

    /**
     * Sets the value of the tripsParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRParameter }
     *     
     */
    public void setTripsParams(ArrayOfRParameter value) {
        this.tripsParams = value;
    }

}
