//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RPropertyTareTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RPropertyTareTable"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Approximation" type="{http://tempuri.org/}RTareTableApproximation"/&gt;
 *         &lt;element name="DependsOnSupply" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Items" type="{http://tempuri.org/}ArrayOfRPropertyTareTableItem" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RPropertyTareTable", propOrder = {
    "approximation",
    "dependsOnSupply",
    "items"
})
public class RPropertyTareTable {

    @XmlElement(name = "Approximation", required = true)
    @XmlSchemaType(name = "string")
    protected RTareTableApproximation approximation;
    @XmlElement(name = "DependsOnSupply")
    protected boolean dependsOnSupply;
    @XmlElement(name = "Items")
    protected ArrayOfRPropertyTareTableItem items;

    /**
     * Gets the value of the approximation property.
     * 
     * @return
     *     possible object is
     *     {@link RTareTableApproximation }
     *     
     */
    public RTareTableApproximation getApproximation() {
        return approximation;
    }

    /**
     * Sets the value of the approximation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTareTableApproximation }
     *     
     */
    public void setApproximation(RTareTableApproximation value) {
        this.approximation = value;
    }

    /**
     * Gets the value of the dependsOnSupply property.
     * 
     */
    public boolean isDependsOnSupply() {
        return dependsOnSupply;
    }

    /**
     * Sets the value of the dependsOnSupply property.
     * 
     */
    public void setDependsOnSupply(boolean value) {
        this.dependsOnSupply = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRPropertyTareTableItem }
     *     
     */
    public ArrayOfRPropertyTareTableItem getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRPropertyTareTableItem }
     *     
     */
    public void setItems(ArrayOfRPropertyTareTableItem value) {
        this.items = value;
    }

}
