//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RPropertyTareTableItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RPropertyTareTableItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Input" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Output" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Supply" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RPropertyTareTableItem", propOrder = {
    "input",
    "output",
    "supply"
})
public class RPropertyTareTableItem {

    @XmlElement(name = "Input", required = true, type = Double.class, nillable = true)
    protected Double input;
    @XmlElement(name = "Output", required = true, type = Double.class, nillable = true)
    protected Double output;
    @XmlElement(name = "Supply", required = true, type = Double.class, nillable = true)
    protected Double supply;

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInput(Double value) {
        this.input = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOutput(Double value) {
        this.output = value;
    }

    /**
     * Gets the value of the supply property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSupply() {
        return supply;
    }

    /**
     * Sets the value of the supply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSupply(Double value) {
        this.supply = value;
    }

}
