//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RPropType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RPropType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="String"/&gt;
 *     &lt;enumeration value="Number"/&gt;
 *     &lt;enumeration value="Date"/&gt;
 *     &lt;enumeration value="TareTable"/&gt;
 *     &lt;enumeration value="Time"/&gt;
 *     &lt;enumeration value="Memo"/&gt;
 *     &lt;enumeration value="Color"/&gt;
 *     &lt;enumeration value="Bool"/&gt;
 *     &lt;enumeration value="Radio"/&gt;
 *     &lt;enumeration value="Image"/&gt;
 *     &lt;enumeration value="File"/&gt;
 *     &lt;enumeration value="ProgressBar"/&gt;
 *     &lt;enumeration value="Combobox"/&gt;
 *     &lt;enumeration value="FileLink"/&gt;
 *     &lt;enumeration value="Device"/&gt;
 *     &lt;enumeration value="GeoFence"/&gt;
 *     &lt;enumeration value="Driver"/&gt;
 *     &lt;enumeration value="Implement"/&gt;
 *     &lt;enumeration value="Task"/&gt;
 *     &lt;enumeration value="CheckDays"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RPropType")
@XmlEnum
public enum RPropType {

    @XmlEnumValue("String")
    STRING("String"),
    @XmlEnumValue("Number")
    NUMBER("Number"),
    @XmlEnumValue("Date")
    DATE("Date"),
    @XmlEnumValue("TareTable")
    TARE_TABLE("TareTable"),
    @XmlEnumValue("Time")
    TIME("Time"),
    @XmlEnumValue("Memo")
    MEMO("Memo"),
    @XmlEnumValue("Color")
    COLOR("Color"),
    @XmlEnumValue("Bool")
    BOOL("Bool"),
    @XmlEnumValue("Radio")
    RADIO("Radio"),
    @XmlEnumValue("Image")
    IMAGE("Image"),
    @XmlEnumValue("File")
    FILE("File"),
    @XmlEnumValue("ProgressBar")
    PROGRESS_BAR("ProgressBar"),
    @XmlEnumValue("Combobox")
    COMBOBOX("Combobox"),
    @XmlEnumValue("FileLink")
    FILE_LINK("FileLink"),
    @XmlEnumValue("Device")
    DEVICE("Device"),
    @XmlEnumValue("GeoFence")
    GEO_FENCE("GeoFence"),
    @XmlEnumValue("Driver")
    DRIVER("Driver"),
    @XmlEnumValue("Implement")
    IMPLEMENT("Implement"),
    @XmlEnumValue("Task")
    TASK("Task"),
    @XmlEnumValue("CheckDays")
    CHECK_DAYS("CheckDays");
    private final String value;

    RPropType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RPropType fromValue(String v) {
        for (RPropType c: RPropType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
