//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RSchedulePeriodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RSchedulePeriodType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UserDefined"/&gt;
 *     &lt;enumeration value="SinceStartHour"/&gt;
 *     &lt;enumeration value="SinceStartDay"/&gt;
 *     &lt;enumeration value="SinceStartWeek"/&gt;
 *     &lt;enumeration value="SinceStartMonth"/&gt;
 *     &lt;enumeration value="LastHour"/&gt;
 *     &lt;enumeration value="LastDay"/&gt;
 *     &lt;enumeration value="LastWeek"/&gt;
 *     &lt;enumeration value="LastMonth"/&gt;
 *     &lt;enumeration value="PrevHour"/&gt;
 *     &lt;enumeration value="PrevDay"/&gt;
 *     &lt;enumeration value="PrevWeek"/&gt;
 *     &lt;enumeration value="PrevMonth"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RSchedulePeriodType")
@XmlEnum
public enum RSchedulePeriodType {

    @XmlEnumValue("UserDefined")
    USER_DEFINED("UserDefined"),
    @XmlEnumValue("SinceStartHour")
    SINCE_START_HOUR("SinceStartHour"),
    @XmlEnumValue("SinceStartDay")
    SINCE_START_DAY("SinceStartDay"),
    @XmlEnumValue("SinceStartWeek")
    SINCE_START_WEEK("SinceStartWeek"),
    @XmlEnumValue("SinceStartMonth")
    SINCE_START_MONTH("SinceStartMonth"),
    @XmlEnumValue("LastHour")
    LAST_HOUR("LastHour"),
    @XmlEnumValue("LastDay")
    LAST_DAY("LastDay"),
    @XmlEnumValue("LastWeek")
    LAST_WEEK("LastWeek"),
    @XmlEnumValue("LastMonth")
    LAST_MONTH("LastMonth"),
    @XmlEnumValue("PrevHour")
    PREV_HOUR("PrevHour"),
    @XmlEnumValue("PrevDay")
    PREV_DAY("PrevDay"),
    @XmlEnumValue("PrevWeek")
    PREV_WEEK("PrevWeek"),
    @XmlEnumValue("PrevMonth")
    PREV_MONTH("PrevMonth");
    private final String value;

    RSchedulePeriodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RSchedulePeriodType fromValue(String v) {
        for (RSchedulePeriodType c: RSchedulePeriodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
