//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTask"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StrictOrder" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="GeofencesTime" type="{http://tempuri.org/}TimeSpan"/&gt;
 *         &lt;element name="Geofences" type="{http://tempuri.org/}ArrayOfRTaskGeofence" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTask", propOrder = {
    "id",
    "name",
    "strictOrder",
    "geofencesTime",
    "geofences"
})
public class RTask {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "StrictOrder")
    protected boolean strictOrder;
    @XmlElement(name = "GeofencesTime", required = true, nillable = true)
    protected TimeSpan geofencesTime;
    @XmlElement(name = "Geofences")
    protected ArrayOfRTaskGeofence geofences;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the strictOrder property.
     * 
     */
    public boolean isStrictOrder() {
        return strictOrder;
    }

    /**
     * Sets the value of the strictOrder property.
     * 
     */
    public void setStrictOrder(boolean value) {
        this.strictOrder = value;
    }

    /**
     * Gets the value of the geofencesTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getGeofencesTime() {
        return geofencesTime;
    }

    /**
     * Sets the value of the geofencesTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setGeofencesTime(TimeSpan value) {
        this.geofencesTime = value;
    }

    /**
     * Gets the value of the geofences property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRTaskGeofence }
     *     
     */
    public ArrayOfRTaskGeofence getGeofences() {
        return geofences;
    }

    /**
     * Sets the value of the geofences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRTaskGeofence }
     *     
     */
    public void setGeofences(ArrayOfRTaskGeofence value) {
        this.geofences = value;
    }

}
