//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RTaskInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTaskInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CurrentTaskID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="CurrentTaskStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="CurrentTaskEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="AllTasks" type="{http://tempuri.org/}ArrayOfRTask" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTaskInfo", propOrder = {
    "currentTaskID",
    "currentTaskStart",
    "currentTaskEnd",
    "allTasks"
})
@XmlSeeAlso({
    RTaskInfo1C.class
})
public class RTaskInfo {

    @XmlElement(name = "CurrentTaskID", required = true, nillable = true)
    protected String currentTaskID;
    @XmlElement(name = "CurrentTaskStart", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar currentTaskStart;
    @XmlElement(name = "CurrentTaskEnd", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar currentTaskEnd;
    @XmlElement(name = "AllTasks")
    protected ArrayOfRTask allTasks;

    /**
     * Gets the value of the currentTaskID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentTaskID() {
        return currentTaskID;
    }

    /**
     * Sets the value of the currentTaskID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentTaskID(String value) {
        this.currentTaskID = value;
    }

    /**
     * Gets the value of the currentTaskStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrentTaskStart() {
        return currentTaskStart;
    }

    /**
     * Sets the value of the currentTaskStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrentTaskStart(XMLGregorianCalendar value) {
        this.currentTaskStart = value;
    }

    /**
     * Gets the value of the currentTaskEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrentTaskEnd() {
        return currentTaskEnd;
    }

    /**
     * Sets the value of the currentTaskEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrentTaskEnd(XMLGregorianCalendar value) {
        this.currentTaskEnd = value;
    }

    /**
     * Gets the value of the allTasks property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRTask }
     *     
     */
    public ArrayOfRTask getAllTasks() {
        return allTasks;
    }

    /**
     * Sets the value of the allTasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRTask }
     *     
     */
    public void setAllTasks(ArrayOfRTask value) {
        this.allTasks = value;
    }

}
