//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTrackInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTrackInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Index" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DT" type="{http://tempuri.org/}ArrayOfDateTime" minOccurs="0"/&gt;
 *         &lt;element name="Speed" type="{http://tempuri.org/}ArrayOfDouble" minOccurs="0"/&gt;
 *         &lt;element name="Lat" type="{http://tempuri.org/}ArrayOfDouble" minOccurs="0"/&gt;
 *         &lt;element name="Lng" type="{http://tempuri.org/}ArrayOfDouble" minOccurs="0"/&gt;
 *         &lt;element name="Photos" type="{http://tempuri.org/}ArrayOfRTrackInfoPhoto" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTrackInfo", propOrder = {
    "index",
    "dt",
    "speed",
    "lat",
    "lng",
    "photos"
})
public class RTrackInfo {

    @XmlElement(name = "Index")
    protected int index;
    @XmlElement(name = "DT")
    protected ArrayOfDateTime dt;
    @XmlElement(name = "Speed")
    protected ArrayOfDouble speed;
    @XmlElement(name = "Lat")
    protected ArrayOfDouble lat;
    @XmlElement(name = "Lng")
    protected ArrayOfDouble lng;
    @XmlElement(name = "Photos")
    protected ArrayOfRTrackInfoPhoto photos;

    /**
     * Gets the value of the index property.
     * 
     */
    public int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     */
    public void setIndex(int value) {
        this.index = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDateTime }
     *     
     */
    public ArrayOfDateTime getDT() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDateTime }
     *     
     */
    public void setDT(ArrayOfDateTime value) {
        this.dt = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDouble }
     *     
     */
    public ArrayOfDouble getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDouble }
     *     
     */
    public void setSpeed(ArrayOfDouble value) {
        this.speed = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDouble }
     *     
     */
    public ArrayOfDouble getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDouble }
     *     
     */
    public void setLat(ArrayOfDouble value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lng property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDouble }
     *     
     */
    public ArrayOfDouble getLng() {
        return lng;
    }

    /**
     * Sets the value of the lng property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDouble }
     *     
     */
    public void setLng(ArrayOfDouble value) {
        this.lng = value;
    }

    /**
     * Gets the value of the photos property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRTrackInfoPhoto }
     *     
     */
    public ArrayOfRTrackInfoPhoto getPhotos() {
        return photos;
    }

    /**
     * Sets the value of the photos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRTrackInfoPhoto }
     *     
     */
    public void setPhotos(ArrayOfRTrackInfoPhoto value) {
        this.photos = value;
    }

}
