//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RTripRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTripRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IsMain" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="SD" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ED" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="tripSplitterIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="onlyTotal" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="areaIDs" type="{http://tempuri.org/}ArrayOfGuid" minOccurs="0"/&gt;
 *         &lt;element name="geofenceIDs" type="{http://tempuri.org/}ArrayOfGuid" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTripRequest", propOrder = {
    "isMain",
    "id",
    "sd",
    "ed",
    "tripSplitterIndex",
    "onlyTotal",
    "areaIDs",
    "geofenceIDs"
})
public class RTripRequest {

    @XmlElement(name = "IsMain")
    protected boolean isMain;
    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "SD", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sd;
    @XmlElement(name = "ED", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ed;
    protected int tripSplitterIndex;
    protected boolean onlyTotal;
    protected ArrayOfGuid areaIDs;
    protected ArrayOfGuid geofenceIDs;

    /**
     * Gets the value of the isMain property.
     * 
     */
    public boolean isIsMain() {
        return isMain;
    }

    /**
     * Sets the value of the isMain property.
     * 
     */
    public void setIsMain(boolean value) {
        this.isMain = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the sd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSD() {
        return sd;
    }

    /**
     * Sets the value of the sd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSD(XMLGregorianCalendar value) {
        this.sd = value;
    }

    /**
     * Gets the value of the ed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getED() {
        return ed;
    }

    /**
     * Sets the value of the ed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setED(XMLGregorianCalendar value) {
        this.ed = value;
    }

    /**
     * Gets the value of the tripSplitterIndex property.
     * 
     */
    public int getTripSplitterIndex() {
        return tripSplitterIndex;
    }

    /**
     * Sets the value of the tripSplitterIndex property.
     * 
     */
    public void setTripSplitterIndex(int value) {
        this.tripSplitterIndex = value;
    }

    /**
     * Gets the value of the onlyTotal property.
     * 
     */
    public boolean isOnlyTotal() {
        return onlyTotal;
    }

    /**
     * Sets the value of the onlyTotal property.
     * 
     */
    public void setOnlyTotal(boolean value) {
        this.onlyTotal = value;
    }

    /**
     * Gets the value of the areaIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfGuid }
     *     
     */
    public ArrayOfGuid getAreaIDs() {
        return areaIDs;
    }

    /**
     * Sets the value of the areaIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfGuid }
     *     
     */
    public void setAreaIDs(ArrayOfGuid value) {
        this.areaIDs = value;
    }

    /**
     * Gets the value of the geofenceIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfGuid }
     *     
     */
    public ArrayOfGuid getGeofenceIDs() {
        return geofenceIDs;
    }

    /**
     * Sets the value of the geofenceIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfGuid }
     *     
     */
    public void setGeofenceIDs(ArrayOfGuid value) {
        this.geofenceIDs = value;
    }

}
