//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTripStage1C complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTripStage1C"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Alias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Params" type="{http://tempuri.org/}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="ParamTypes" type="{http://tempuri.org/}ArrayOfReturnType" minOccurs="0"/&gt;
 *         &lt;element name="Items" type="{http://tempuri.org/}ArrayOfRTripStageItem" minOccurs="0"/&gt;
 *         &lt;element name="Statuses" type="{http://tempuri.org/}ArrayOfRParameterStatus" minOccurs="0"/&gt;
 *         &lt;element name="Total" type="{http://tempuri.org/}ArrayOfRObjectValue1C" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTripStage1C", propOrder = {
    "id",
    "name",
    "alias",
    "params",
    "paramTypes",
    "items",
    "statuses",
    "total"
})
public class RTripStage1C {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Alias")
    protected String alias;
    @XmlElement(name = "Params")
    protected ArrayOfString params;
    @XmlElement(name = "ParamTypes")
    protected ArrayOfReturnType paramTypes;
    @XmlElement(name = "Items")
    protected ArrayOfRTripStageItem items;
    @XmlElement(name = "Statuses")
    protected ArrayOfRParameterStatus statuses;
    @XmlElement(name = "Total")
    protected ArrayOfRObjectValue1C total;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setParams(ArrayOfString value) {
        this.params = value;
    }

    /**
     * Gets the value of the paramTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfReturnType }
     *     
     */
    public ArrayOfReturnType getParamTypes() {
        return paramTypes;
    }

    /**
     * Sets the value of the paramTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfReturnType }
     *     
     */
    public void setParamTypes(ArrayOfReturnType value) {
        this.paramTypes = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRTripStageItem }
     *     
     */
    public ArrayOfRTripStageItem getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRTripStageItem }
     *     
     */
    public void setItems(ArrayOfRTripStageItem value) {
        this.items = value;
    }

    /**
     * Gets the value of the statuses property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRParameterStatus }
     *     
     */
    public ArrayOfRParameterStatus getStatuses() {
        return statuses;
    }

    /**
     * Sets the value of the statuses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRParameterStatus }
     *     
     */
    public void setStatuses(ArrayOfRParameterStatus value) {
        this.statuses = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRObjectValue1C }
     *     
     */
    public ArrayOfRObjectValue1C getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRObjectValue1C }
     *     
     */
    public void setTotal(ArrayOfRObjectValue1C value) {
        this.total = value;
    }

}
