//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RTripTableItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTripTableItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Index" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SD" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ED" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="PointStart" type="{http://tempuri.org/}RPoint" minOccurs="0"/&gt;
 *         &lt;element name="PointEnd" type="{http://tempuri.org/}RPoint" minOccurs="0"/&gt;
 *         &lt;element name="DT" type="{http://tempuri.org/}ArrayOfDateTime" minOccurs="0"/&gt;
 *         &lt;element name="Values" type="{http://tempuri.org/}ArrayOfRTripTableValues" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTripTableItem", propOrder = {
    "index",
    "sd",
    "ed",
    "pointStart",
    "pointEnd",
    "dt",
    "values"
})
public class RTripTableItem {

    @XmlElement(name = "Index")
    protected int index;
    @XmlElement(name = "SD", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sd;
    @XmlElement(name = "ED", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ed;
    @XmlElement(name = "PointStart")
    protected RPoint pointStart;
    @XmlElement(name = "PointEnd")
    protected RPoint pointEnd;
    @XmlElement(name = "DT")
    protected ArrayOfDateTime dt;
    @XmlElement(name = "Values")
    protected ArrayOfRTripTableValues values;

    /**
     * Gets the value of the index property.
     * 
     */
    public int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     */
    public void setIndex(int value) {
        this.index = value;
    }

    /**
     * Gets the value of the sd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSD() {
        return sd;
    }

    /**
     * Sets the value of the sd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSD(XMLGregorianCalendar value) {
        this.sd = value;
    }

    /**
     * Gets the value of the ed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getED() {
        return ed;
    }

    /**
     * Sets the value of the ed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setED(XMLGregorianCalendar value) {
        this.ed = value;
    }

    /**
     * Gets the value of the pointStart property.
     * 
     * @return
     *     possible object is
     *     {@link RPoint }
     *     
     */
    public RPoint getPointStart() {
        return pointStart;
    }

    /**
     * Sets the value of the pointStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link RPoint }
     *     
     */
    public void setPointStart(RPoint value) {
        this.pointStart = value;
    }

    /**
     * Gets the value of the pointEnd property.
     * 
     * @return
     *     possible object is
     *     {@link RPoint }
     *     
     */
    public RPoint getPointEnd() {
        return pointEnd;
    }

    /**
     * Sets the value of the pointEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link RPoint }
     *     
     */
    public void setPointEnd(RPoint value) {
        this.pointEnd = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDateTime }
     *     
     */
    public ArrayOfDateTime getDT() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDateTime }
     *     
     */
    public void setDT(ArrayOfDateTime value) {
        this.dt = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRTripTableValues }
     *     
     */
    public ArrayOfRTripTableValues getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRTripTableValues }
     *     
     */
    public void setValues(ArrayOfRTripTableValues value) {
        this.values = value;
    }

}
