//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.18 at 06:19:32 PM MSK 
//


package ru.tdv.soapclient.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTripArea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTripArea"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ColorR" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="ColorG" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="ColorB" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="Polygons" type="{http://tempuri.org/}ArrayOfArrayOfArrayOfDouble" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTripArea", propOrder = {
    "colorR",
    "colorG",
    "colorB",
    "polygons"
})
public class RTripArea {

    @XmlElement(name = "ColorR")
    @XmlSchemaType(name = "unsignedByte")
    protected short colorR;
    @XmlElement(name = "ColorG")
    @XmlSchemaType(name = "unsignedByte")
    protected short colorG;
    @XmlElement(name = "ColorB")
    @XmlSchemaType(name = "unsignedByte")
    protected short colorB;
    @XmlElement(name = "Polygons")
    protected ArrayOfArrayOfArrayOfDouble polygons;

    /**
     * Gets the value of the colorR property.
     * 
     */
    public short getColorR() {
        return colorR;
    }

    /**
     * Sets the value of the colorR property.
     * 
     */
    public void setColorR(short value) {
        this.colorR = value;
    }

    /**
     * Gets the value of the colorG property.
     * 
     */
    public short getColorG() {
        return colorG;
    }

    /**
     * Sets the value of the colorG property.
     * 
     */
    public void setColorG(short value) {
        this.colorG = value;
    }

    /**
     * Gets the value of the colorB property.
     * 
     */
    public short getColorB() {
        return colorB;
    }

    /**
     * Sets the value of the colorB property.
     * 
     */
    public void setColorB(short value) {
        this.colorB = value;
    }

    /**
     * Gets the value of the polygons property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfArrayOfArrayOfDouble }
     *     
     */
    public ArrayOfArrayOfArrayOfDouble getPolygons() {
        return polygons;
    }

    /**
     * Sets the value of the polygons property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfArrayOfArrayOfDouble }
     *     
     */
    public void setPolygons(ArrayOfArrayOfArrayOfDouble value) {
        this.polygons = value;
    }

}
